(()=>{'use strict';
const TEAMS=['대형메인팀','휠로더Front팀','대형Att.팀','휠로더리어팀','중형상부1팀','중형메인팀','중형Att팀','대형상부팀','프레임제작팀','휠로더메인팀','중형상부2팀','중형하부팀','Boom제작팀','초대형조립팀','성능팀','트러블슈팅팀'];
const ORDER_KEY='gmes5s_team_display_order',TARGET_KEY='gmes5s_quarter_targets';
let teamOrder=[...TEAMS],targetMaster={Q1:45,Q2:50,Q3:55,Q4:60};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function loadSettings(){try{const v=JSON.parse(localStorage.getItem(ORDER_KEY)||'null');if(Array.isArray(v)&&v.length===TEAMS.length&&TEAMS.every(t=>v.includes(t)))teamOrder=v}catch{}try{const v=JSON.parse(localStorage.getItem(TARGET_KEY)||'null');if(v&&typeof v==='object')targetMaster={...targetMaster,...v}}catch{}}
function snapshot(){if(window.HD20KPIData?.snapshot)return window.HD20KPIData.snapshot();try{const rows=JSON.parse(localStorage.getItem('hd20GMES5SAutoImproveRawV1')||'[]');return{activities:Array.isArray(rows)?rows:[],candidates:[],newSecured:[]}}catch{return{activities:[],candidates:[],newSecured:[]}}}
function teamOf(x){return String(x?.team||'').trim()}
function counts(){const s=snapshot(),out=new Map(TEAMS.map(t=>[t,{activity:0,candidate:0,secured:0}]));(s.activities||[]).forEach(x=>{const d=out.get(teamOf(x));if(d)d.activity++});(s.candidates||[]).forEach(x=>{const d=out.get(teamOf(x));if(d)d.candidate++});(s.newSecured||[]).forEach(x=>{const d=out.get(teamOf(x));if(d)d.secured++});return out}
function quarter(){const m=new Date().getMonth()+1;return m<=3?'Q1':m<=6?'Q2':m<=9?'Q3':'Q4'}
function renderTargetLine(){const q=quarter(),v=Number(targetMaster[q]||0),line=$('#targetLine'),label=$('#targetLabel');if(line)line.style.top=Math.max(0,Math.min(100,(1-v/Math.max(1,v,80))*100))+'%';if(label)label.textContent=`${q} 목표 ${v}건`}
function renderChart(){const root=$('#cols');if(!root)return;const map=counts(),vals=teamOrder.map(t=>map.get(t)||{activity:0,candidate:0,secured:0}),maxA=Math.max(1,...vals.map(x=>x.activity)),maxC=Math.max(1,...vals.map(x=>x.candidate)),maxS=Math.max(1,...vals.map(x=>x.secured));root.innerHTML=teamOrder.map((t,i)=>{const d=vals[i];return`<div class="grp"><div class="bar blue" style="height:${Math.max(d.activity?4:0,d.activity/maxA*235)}px"><em>${d.activity}</em></div><div class="bar orange" style="height:${Math.max(d.candidate?4:0,d.candidate/maxC*92)}px"><em>${d.candidate}</em></div><div class="bar green" style="height:${Math.max(d.secured?4:0,d.secured/maxS*76)}px"><em>${d.secured}</em></div><label>${t}</label></div>`}).join('');renderTargetLine()}
function renderOrderEditor(){const list=$('#orderList');if(!list)return;list.innerHTML=teamOrder.map((t,i)=>`<div class="orderRow"><div class="orderNo">${i+1}</div><div class="orderName">${t}</div><div class="orderBtns"><button type="button" data-act="up" data-i="${i}">▲</button><button type="button" data-act="down" data-i="${i}">▼</button></div></div>`).join('');$$('[data-act]',list).forEach(btn=>btn.onclick=()=>{const i=+btn.dataset.i;if(btn.dataset.act==='up'&&i>0)[teamOrder[i-1],teamOrder[i]]=[teamOrder[i],teamOrder[i-1]];if(btn.dataset.act==='down'&&i<teamOrder.length-1)[teamOrder[i+1],teamOrder[i]]=[teamOrder[i],teamOrder[i+1]];renderOrderEditor()})}
function loadTargets(){['Q1','Q2','Q3','Q4'].forEach((q,i)=>{const e=$(`#q${i+1}Target`);if(e)e.value=Number(targetMaster[q]||0)})}
function initMaster(){const modal=$('#masterModal');const open=$('#openMaster'),close=$('#closeMaster'),cancel=$('#cancelOrder'),save=$('#saveOrder'),tabs=$$('[data-master-tab]');let tab='order';const setTab=t=>{tab=t;tabs.forEach(b=>b.classList.toggle('on',b.dataset.masterTab===t));const order=$('#masterOrderPanel'),target=$('#masterTargetPanel');if(order)order.style.display=t==='order'?'block':'none';if(target)target.style.display=t==='target'?'block':'none';if(t==='order')renderOrderEditor();else loadTargets()};if(open)open.onclick=()=>{modal?.classList.add('on');setTab('order')};if(close)close.onclick=()=>modal?.classList.remove('on');if(cancel)cancel.onclick=()=>modal?.classList.remove('on');tabs.forEach(b=>b.onclick=()=>setTab(b.dataset.masterTab));if(save)save.onclick=()=>{if(tab==='order')localStorage.setItem(ORDER_KEY,JSON.stringify(teamOrder));else{targetMaster={Q1:+($('#q1Target')?.value||0),Q2:+($('#q2Target')?.value||0),Q3:+($('#q3Target')?.value||0),Q4:+($('#q4Target')?.value||0)};localStorage.setItem(TARGET_KEY,JSON.stringify(targetMaster))}renderChart();modal?.classList.remove('on')}}
function boot(){loadSettings();renderChart();initMaster()}
window.renderChart=renderChart;window.HD20LegacyDashboard={renderChart,counts,teamOrder:()=>[...teamOrder],targets:()=>({...targetMaster})};
['hd20-kpi-source-updated','hd20-gmes-5s-imported','hd20-gmes-5s-judged'].forEach(ev=>window.addEventListener(ev,()=>setTimeout(renderChart,0)));
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();