const augustAudit=[
 {dept:'중형조립과',team:'상부조립1팀',scores:[88,85,86],avg:86.3},{dept:'중형조립과',team:'상부조립2팀',scores:[84,78,80],avg:80.7},{dept:'중형조립과',team:'메인조립팀',scores:[82,77,79],avg:79.3},{dept:'조립1팀',team:'하부조립팀',scores:[85,83,82],avg:83.3},{dept:'조립1팀',team:'Att’조립팀',scores:[84,80,80],avg:81.3},{dept:'대형조립과',team:'상부조립팀',scores:[85,84,83],avg:84.0},{dept:'대형조립과',team:'메인조립팀',scores:[90,87,89],avg:88.7},{dept:'대형조립과',team:'Att’조립팀',scores:[94,90,90],avg:91.3},{dept:'성능과',team:'성능팀',scores:[80,78,78],avg:78.7},{dept:'성능과',team:'T/S팀',scores:[87,80,82],avg:83.0},{dept:'조립2팀',team:'Front조립팀',scores:[95,94,94],avg:94.3},{dept:'조립2팀',team:'Rear조립팀',scores:[94,90,90],avg:91.3},{dept:'휠로더 초대형과',team:'메인조립팀',scores:[84,86,85],avg:85.0},{dept:'조립2팀',team:'옵션공정 지원팀',scores:[94,88,90],avg:90.7},{dept:'조립2팀',team:'초대형조립팀',scores:[90,90,90],avg:90.0},{dept:'제작과',team:'프레임제작팀',scores:[90,87,86],avg:87.7},{dept:'제작과',team:'Boom제작팀',scores:[90,90,90],avg:90.0},{dept:'생산지원',team:'입고·검사팀',scores:[87,87,87],avg:87.0},{dept:'생산지원',team:'출하팀',scores:[65,62,62],avg:63.0},{dept:'생산지원',team:'자재물류팀',scores:[80,77,77],avg:78.0}
];

const completionMonthly={
 '2026-01':{'조립1팀':[14,12],'Rear조립팀':[11,9],'가공1팀':[13,12],'자재운영팀':[10,8],'생산관리팀':[9,7]},
 '2026-02':{'조립1팀':[15,13],'Rear조립팀':[12,10],'가공1팀':[14,13],'자재운영팀':[10,8],'생산관리팀':[9,7]},
 '2026-03':{'조립1팀':[16,14],'Rear조립팀':[12,10],'가공1팀':[15,14],'자재운영팀':[11,8],'생산관리팀':[10,8]},
 '2026-04':{'조립1팀':[15,13],'Rear조립팀':[13,11],'가공1팀':[14,12],'자재운영팀':[11,9],'생산관리팀':[10,8]},
 '2026-05':{'조립1팀':[17,15],'Rear조립팀':[13,11],'가공1팀':[15,13],'자재운영팀':[12,10],'생산관리팀':[10,9]},
 '2026-06':{'조립1팀':[16,14],'Rear조립팀':[14,12],'가공1팀':[16,14],'자재운영팀':[12,10],'생산관리팀':[11,9]},
 '2026-07':{'조립1팀':[18,16],'Rear조립팀':[14,12],'가공1팀':[16,14],'자재운영팀':[13,11],'생산관리팀':[11,9]},
 '2026-08':{'조립1팀':[13,11],'Rear조립팀':[10,9],'가공1팀':[12,11],'자재운영팀':[9,8],'생산관리팀':[8,7]}
};
const completionTeams=['조립1팀','Rear조립팀','가공1팀','자재운영팀','생산관리팀'];
const repeatTrend=[['03월',21.4],['04월',19.8],['05월',18.1],['06월',16.7],['07월',14.9],['08월',12.5]];
const repeatHotspots=[
 {team:'출하팀',dept:'생산지원',total:18,repeat:5,type:'정리·정돈'},
 {team:'메인조립팀',dept:'중형조립과',total:22,repeat:5,type:'정돈·시각화'},
 {team:'자재물류팀',dept:'생산지원',total:17,repeat:3,type:'정리·정돈'},
 {team:'성능팀',dept:'성능과',total:15,repeat:2,type:'청소·시각화'},
 {team:'상부조립2팀',dept:'중형조립과',total:16,repeat:2,type:'정돈'}
].map(x=>({...x,rate:x.repeat/x.total*100}));

const pad2=n=>String(n).padStart(2,'0');
const fmt=d=>`${d.getFullYear()}.${pad2(d.getMonth()+1)}.${pad2(d.getDate())}`;
const today=()=>new Date();
function startMonth(){const e=document.getElementById('monthFilter'),n=Number(e?.value||1);return Math.min(Math.max(Math.trunc(n)||1,1),today().getMonth()+1)}
function range(){const d=today(),m=startMonth();return{start:new Date(d.getFullYear(),m-1,1),end:d,m}}
function monthsInRange(){const r=range(),out=[];for(let m=r.m;m<=r.end.getMonth()+1;m++)out.push(`${r.end.getFullYear()}-${pad2(m)}`);return out}

function injectStyles(){
 if(document.getElementById('storylineStyle'))return;
 const s=document.createElement('style');s.id='storylineStyle';s.textContent=`
 .period-filter-hint{display:block;font-size:9px;color:#98a2b3}.dashboard-scope-badge{margin:-7px 0 14px;padding:10px 14px;border:1px solid #d9e5ec;border-left:4px solid #087fb1;border-radius:8px;background:#f8fbfd;display:flex;gap:10px;align-items:center;font-size:11px}.dashboard-scope-badge span{font-weight:800;color:#087fb1}.dashboard-scope-badge em{margin-left:auto;font-style:normal;color:#667085}
 .story-section{margin:18px 0 24px}.story-head{display:flex;align-items:center;gap:12px;margin:0 0 10px}.story-step{width:28px;height:28px;border-radius:50%;background:#0b789f;color:#fff;display:grid;place-items:center;font-weight:800;font-size:12px}.story-head h2{margin:0;font-size:18px;color:#172b4d}.story-head p{margin:3px 0 0;font-size:11px;color:#7b8794}.story-rule{height:1px;flex:1;background:#dfe6ec}
 .metric-grid-merged{display:block!important}.merged-productivity-chart{height:260px;padding:22px 34px 16px;display:flex;align-items:flex-end;gap:28px}.merged-team-group{flex:1;text-align:center}.merged-bars{height:198px;display:flex;align-items:flex-end;justify-content:center;gap:9px;border-bottom:1px solid #d5dde6}.merged-bar-wrap{height:100%;width:40px;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:4px}.merged-bar{width:32px;border-radius:5px 5px 0 0}.merged-bar.improve{background:#48779a}.merged-bar.standard{background:#6f9d71}.merged-team-group>strong{font-size:11px;color:#344054}
 .diagnostic-grid{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(420px,.65fr);gap:14px;align-items:start}.august-audit-panel{margin:0}.audit-summary{display:flex;gap:7px;flex-wrap:wrap}.audit-summary span{padding:6px 9px;background:#f6f8fa;border:1px solid #e5e9ef;border-radius:7px;font-size:10px}.audit-note{margin:0 16px 10px;padding:9px 11px;background:#fff9e8;border-radius:7px;font-size:10px;color:#6b5a20}.audit-score-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px 18px;padding:7px 16px 16px}.audit-score-row{display:grid;grid-template-columns:120px 1fr 40px;gap:8px;align-items:center}.audit-score-row strong{display:block;font-size:10px}.audit-score-row small{display:block;color:#98a2b3;font-size:8px}.audit-score-track{height:7px;background:#edf1f4;border-radius:99px;overflow:hidden}.audit-score-track i{display:block;height:100%;background:#5d8faf;border-radius:99px}.audit-score{font-size:11px;text-align:right}.audit-score.watch{color:#c57b00}.audit-score.risk{color:#c43b3b}
 .repeat-panel .panel-head{align-items:flex-start}.repeat-body{padding:14px 16px 16px}.repeat-trend{height:160px;display:flex;align-items:flex-end;gap:12px;border-bottom:1px solid #d7dee6;padding:8px 4px 0}.repeat-col{flex:1;height:100%;display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:5px}.repeat-col b{font-size:10px}.repeat-bar{width:28px;background:#da8b35;border-radius:5px 5px 0 0}.repeat-col span{font-size:9px;color:#667085}.hot-title{margin:16px 0 3px;font-size:13px}.hot-sub{font-size:9px;color:#8a94a2;margin:0 0 8px}.hot-row{display:grid;grid-template-columns:110px 1fr 52px;gap:8px;align-items:center;margin:9px 0}.hot-name strong{display:block;font-size:10px}.hot-name small{font-size:8px;color:#98a2b3}.hot-track{height:9px;background:#edf1f4;border-radius:99px;overflow:hidden}.hot-track i{display:block;height:100%;border-radius:99px;background:#db8d35}.hot-rate{text-align:right;font-size:11px;font-weight:800}.hot-meta{grid-column:2/4;font-size:8px;color:#7b8794;margin-top:-6px}
 .execution-grid{display:grid;grid-template-columns:1fr;gap:14px}.execution-grid .completion-panel{width:100%}.secondary-grid{display:contents!important}.detail-panel{margin-top:0}.story-section .panel{box-shadow:0 1px 2px rgba(16,24,40,.04)}
 @media(max-width:1100px){.diagnostic-grid{grid-template-columns:1fr}.audit-score-grid{grid-template-columns:1fr}.merged-productivity-chart{overflow-x:auto}.merged-team-group{min-width:120px}}
 `;document.head.appendChild(s)
}

function configurePeriod(){const e=document.getElementById('monthFilter');if(!e)return;e.type='number';e.min='1';e.max=String(today().getMonth()+1);e.value='';e.placeholder='미입력 = 1월';const l=e.closest('label');if(l){Array.from(l.childNodes).forEach(n=>{if(n.nodeType===3&&n.textContent.trim())n.textContent='조회 시작월 '});if(!l.querySelector('.period-filter-hint')){const h=document.createElement('small');h.className='period-filter-hint';h.textContent='미입력 시 1월부터 누계';l.appendChild(h)}}const f=document.querySelector('.dashboard-filter');if(f&&!document.getElementById('dashboardScopeBadge')){const b=document.createElement('div');b.id='dashboardScopeBadge';b.className='dashboard-scope-badge';f.after(b)}updateScope()}
function updateScope(){const r=range(),b=document.getElementById('dashboardScopeBadge');if(b)b.innerHTML=`<span>조회기간</span><strong>${fmt(r.start)} ~ ${fmt(r.end)}</strong><em>${r.m===1?'당해년도 YTD 누계':`${r.m}월 1일부터 현재일까지 누계`}</em>`}

function renderMerged(){const g=document.querySelector('.metric-grid');if(!g||typeof perCapita==='undefined'||typeof standardPerCapita==='undefined')return;const sm=Object.fromEntries(standardPerCapita),rows=perCapita.map(([t,v])=>[t,v,sm[t]||0]),mx=Math.max(...rows.flatMap(r=>[r[1],r[2]]),1),r=range();g.classList.add('metric-grid-merged');g.innerHTML=`<article class="panel"><div class="panel-head"><div><h2>팀별 인당 5S 개선성과</h2><p>${fmt(r.start)} ~ ${fmt(r.end)} 누계 · 팀 총원 기준 환산</p></div><span class="metric-unit">개선 / 표준화 · 건/인</span></div><div class="merged-productivity-chart">${rows.map(([t,a,b])=>`<div class="merged-team-group"><div class="merged-bars"><div class="merged-bar-wrap"><span>${a.toFixed(1)}</span><div class="merged-bar improve" style="height:${Math.max(14,a/mx*180)}px"></div></div><div class="merged-bar-wrap"><span>${b.toFixed(1)}</span><div class="merged-bar standard" style="height:${Math.max(14,b/mx*180)}px"></div></div></div><strong>${t}</strong></div>`).join('')}</div></article>`}

function renderAudit(){const anchor=document.querySelector('.secondary-grid');if(!anchor||document.getElementById('augustAuditPanel'))return;const av=augustAudit.reduce((s,x)=>s+x.avg,0)/augustAudit.length,min=Math.min(...augustAudit.map(x=>x.avg)),max=Math.max(...augustAudit.map(x=>x.avg));const p=document.createElement('article');p.id='augustAuditPanel';p.className='panel august-audit-panel';p.innerHTML=`<div class="panel-head"><div><h2>8월 생산현장 5S Audit 실측 결과</h2><p>5S 모듈리더·활동멤버 주관 · 19개 현장팀 실제 평가</p></div><div class="audit-summary"><span>평균 <b>${av.toFixed(1)}</b></span><span>최고 <b>${max.toFixed(1)}</b></span><span>최저 <b>${min.toFixed(1)}</b></span><span>대상 <b>${augustAudit.length}개 팀</b></span></div></div><div class="audit-note"><b>점수 자체보다 팀 간 편차와 저점 작업장을 식별</b>하고, 미흡사항을 개선요청·반복지적 관리로 연결합니다.</div><div class="audit-score-grid">${augustAudit.map(x=>`<div class="audit-score-row"><div><strong>${x.team}</strong><small>${x.dept}</small></div><div class="audit-score-track"><i style="width:${x.avg}%"></i></div><b class="audit-score ${x.avg<75?'risk':x.avg<85?'watch':''}">${x.avg.toFixed(1)}</b></div>`).join('')}</div>`;anchor.parentNode.insertBefore(p,anchor)}

function renderRepeatPanel(){const secondary=document.querySelector('.secondary-grid');if(!secondary)return;const old=secondary.querySelector('.panel:not(.completion-panel)');if(!old)return;old.classList.add('repeat-panel');old.innerHTML=`<div class="panel-head"><div><h2>반복지적 분석</h2><p>추이와 집중 작업장을 함께 보아 재발 리스크를 식별</p></div></div><div class="repeat-body"><div class="repeat-trend">${repeatTrend.map(([m,v])=>`<div class="repeat-col"><b>${v.toFixed(1)}%</b><div class="repeat-bar" style="height:${v/25*115}px"></div><span>${m}</span></div>`).join('')}</div><h3 class="hot-title">반복지적 집중 작업장 TOP 5</h3><p class="hot-sub">비율만이 아닌 반복건수·전체지적건수·주요유형을 함께 판단</p>${repeatHotspots.map((x,i)=>`<div class="hot-row"><div class="hot-name"><strong>${i+1}. ${x.team}</strong><small>${x.dept}</small></div><div class="hot-track"><i style="width:${Math.min(100,x.rate/30*100)}%"></i></div><div class="hot-rate">${x.rate.toFixed(1)}%</div><div class="hot-meta">전체 ${x.total}건 · 반복 ${x.repeat}건 · ${x.type}</div></div>`).join('')}</div>`}

function aggregateCompletion(){const out={};completionTeams.forEach(t=>out[t]=[0,0]);monthsInRange().forEach(m=>{const row=completionMonthly[m]||{};completionTeams.forEach(t=>{const v=row[t]||[0,0];out[t][0]+=v[0];out[t][1]+=v[1]})});return out}
function renderCompletion(){const d=aggregateCompletion(),req=completionTeams.reduce((s,t)=>s+d[t][0],0),done=completionTeams.reduce((s,t)=>s+d[t][1],0),open=req-done,rate=req?done/req*100:0,r=range();const map={completionRequested:req,completionDone:done,completionOpen:open};Object.entries(map).forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v});const e1=document.getElementById('completionRate');if(e1)e1.textContent=`${rate.toFixed(1)}%`;const e2=document.getElementById('completionFormula');if(e2)e2.textContent=`${done} ÷ ${req} × 100`;const e3=document.getElementById('completionPeriodLabel');if(e3)e3.textContent=`${fmt(r.start)} ~ ${fmt(r.end)} · 누계 요청건수 대비 완료건수`;const k=document.getElementById('completionKpiValue');if(k)k.textContent=`${rate.toFixed(1)}%`;const km=document.getElementById('completionKpiMeta');if(km)km.textContent=`누계 ${done} / ${req}건 완료`;const chart=document.getElementById('completionTeamChart');if(chart)chart.innerHTML=completionTeams.map(t=>{const[a,b]=d[t],o=a-b,p=a?b/a*100:0;return `<div class="completion-row"><div class="completion-team"><strong>${t}</strong><span>${b}/${a}건 완료 · 미결 ${o}건</span></div><div class="completion-bar"><span class="completion-done" style="width:${p}%"></span><span class="completion-open" style="width:${100-p}%"></span></div><div class="completion-pct">${p.toFixed(1)}%</div></div>`}).join('')}

function storyHeader(step,title,desc){const h=document.createElement('div');h.className='story-head';h.innerHTML=`<span class="story-step">${step}</span><div><h2>${title}</h2><p>${desc}</p></div><div class="story-rule"></div>`;return h}
function restructureDashboard(){const dash=document.getElementById('dashboard');if(!dash||dash.dataset.story==='1')return;dash.dataset.story='1';const activity=document.querySelector('.activity-panel'),oldSectionTitle=document.querySelector('.section-title'),metric=document.querySelector('.metric-grid'),audit=document.getElementById('augustAuditPanel'),secondary=document.querySelector('.secondary-grid'),completion=secondary?.querySelector('.completion-panel'),repeat=secondary?.querySelector('.repeat-panel'),detail=document.querySelector('.detail-panel');if(oldSectionTitle)oldSectionTitle.remove();
 const s1=document.createElement('section');s1.className='story-section';s1.appendChild(storyHeader('1','활동 수준','무엇을 얼마나 개선했고, 표준화까지 얼마나 이어졌는지 확인'));if(activity)s1.appendChild(activity);if(metric)s1.appendChild(metric);
 const s2=document.createElement('section');s2.className='story-section';s2.appendChild(storyHeader('2','현장 진단','실측 Audit 편차와 반복지적 집중 작업장을 통해 우선 개선대상 식별'));const dg=document.createElement('div');dg.className='diagnostic-grid';if(audit)dg.appendChild(audit);if(repeat)dg.appendChild(repeat);s2.appendChild(dg);
 const s3=document.createElement('section');s3.className='story-section';s3.appendChild(storyHeader('3','개선 실행','개선요청의 완료·미결 상태와 실제 조치내역까지 연결'));const eg=document.createElement('div');eg.className='execution-grid';if(completion)eg.appendChild(completion);if(detail)eg.appendChild(detail);s3.appendChild(eg);
 const kpis=document.querySelector('.focus-kpis');if(kpis){kpis.after(s1);s1.after(s2);s2.after(s3)}if(secondary&&secondary.children.length===0)secondary.remove()}

function fixKpiNarrative(){const cards=[...document.querySelectorAll('.focus-kpis .kpi')];const auditCard=cards.find(c=>c.textContent.includes('5S Audit 평균점수'));if(auditCard){auditCard.querySelector('span').textContent='반복지적률';auditCard.querySelector('strong').textContent='12.5%';auditCard.querySelector('em').textContent='3월 21.4% → 8월 12.5%';const badge=auditCard.querySelector('.kpi-badge');if(badge)badge.textContent='재발'}}

injectStyles();configurePeriod();fixKpiNarrative();renderMerged();renderAudit();renderRepeatPanel();renderCompletion();restructureDashboard();
document.getElementById('monthFilter')?.addEventListener('change',()=>{updateScope();renderMerged();renderCompletion()});
document.getElementById('searchBtn')?.addEventListener('click',()=>{updateScope();renderMerged();renderCompletion()});