(()=>{
const photoSets={
visual:{before:'https://images.unsplash.com/photo-1745449064670-94bd0fc13df8?auto=format&fit=crop&w=900&q=82',after:'https://images.unsplash.com/photo-1773517459502-54c3a9b103a4?auto=format&fit=crop&w=900&q=82'},
green:{before:'https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=900&q=82',after:'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=82'},
space:{before:'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=900&q=82',after:'https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=900&q=82'}
};
const criteriaData=[
{title:'1. 시각화·형적관리를 통한 찾는 낭비 제거',icon:'◉',standards:['눈에 보이는 표준화된 보관과 위치 관리','자재·공구를 제자리에 보관해 탐색시간 최소화','시각표지·라벨링·컬러존으로 한눈에 식별'],site:'대형 Main 작업장',improve:'공구류 형적관리 + 위치라벨 표준화',effect:'찾는 시간 67% 감소 · 작업준비시간 단축',point:'보이는 것이 곧 표준이다.',scene:'visual'},
{title:'2. 인간공학적 Green Zone을 통한 안전·동선 최소화',icon:'○',standards:['작업자 중심 높이·거리·동선을 기준으로 재배치','반복 이동·허리 굽힘·과도한 Reach 최소화','Green Zone 내 자재·공구 사용빈도 기준 배치'],site:'휠로더 Front 작업장',improve:'빈번 사용 부품을 Green Zone에 집중 배치',effect:'이동거리 42% 감소 · 불필요 동작 31% 감소',point:'사람이 가장 편한 위치가 가장 안전한 위치다.',scene:'green'},
{title:'3. 정량축소·정위치 변경을 통한 공간 활용 확장',icon:'◇',standards:['필요량 기준으로 재고·물품 정량 축소','작업 흐름 기준으로 보관 위치 재설계','확보 공간을 작업·통행·안전 공간으로 전환'],site:'Frame 제작 작업장',improve:'적치수량 축소 + 선반 위치 재구성',effect:'작업공간 28% 확장 · 통로 폭 35% 확보',point:'줄이고 옮겨서 공간을 생산성으로 바꾼다.',scene:'space'}
];
function injectStyle(){if(document.getElementById('criteriaHoverStyle'))return;const s=document.createElement('style');s.id='criteriaHoverStyle';s.textContent=`.criteria .crit{cursor:pointer;position:relative}.criteria .crit:after{content:'사례 보기';position:absolute;right:10px;bottom:8px;font-size:9px;font-weight:900;color:#2d6f9d;opacity:0;transform:translateY(3px);transition:.18s}.criteria .crit:hover:after{opacity:1;transform:none}.criteria .crit.criteria-active{border-color:#4b95e6;box-shadow:0 8px 24px rgba(45,111,157,.14);transform:translateY(-2px)}.criteriaCaseLayer{position:fixed;inset:0;background:rgba(13,32,50,.16);z-index:80;pointer-events:none;opacity:0;transition:.18s}.criteriaCaseLayer.on{opacity:1}.criteriaCasePopup{position:fixed;width:min(940px,calc(100vw - 44px));max-height:calc(100vh - 64px);overflow:auto;background:#fff;border:1px solid #b9cfe0;border-radius:14px;box-shadow:0 18px 50px rgba(17,47,73,.26);z-index:81;opacity:0;transform:translateY(10px) scale(.985);pointer-events:none;transition:.2s ease}.criteriaCasePopup.on{opacity:1;transform:none;pointer-events:auto}.ccHead{display:flex;align-items:center;justify-content:space-between;padding:14px 16px;background:linear-gradient(90deg,#0f4590,#0f66be);color:#fff;position:sticky;top:0;z-index:3}.ccHead h3{font-size:17px;margin:0}.ccClose{width:30px;height:30px;border:0;border-radius:50%;background:#ffffff22;color:#fff;font-size:18px;cursor:pointer}.ccBody{padding:14px}.ccGrid{display:grid;grid-template-columns:.8fr 1.2fr;gap:14px}.ccBox{border:1px solid #dde7ee;border-radius:10px;padding:12px;background:#fbfcfd}.ccBox h4{margin:0 0 10px;font-size:13px}.ccStandards{margin:0;padding-left:19px;font-size:11px;line-height:1.7}.ccEffect{margin-top:10px;background:#edf8f0;border:1px solid #d0ead6;border-radius:8px;padding:10px;font-size:11px}.ccPhotos{display:grid;grid-template-columns:1fr 36px 1fr;gap:8px;align-items:center}.ccPhotoWrap{position:relative}.ccPhotoWrap span{position:absolute;left:8px;top:8px;z-index:2;padding:4px 8px;border-radius:12px;background:rgba(17,34,51,.82);color:#fff;font-size:9px;font-weight:900}.ccPhotoWrap.after span{background:rgba(34,137,72,.9)}.ccPhotos img{width:100%;height:190px;object-fit:cover;border-radius:8px;border:1px solid #d2dce3;background:#eef2f5;display:block}.ccArrow{text-align:center;font-size:26px;font-weight:900;color:#2978d3}.ccMeta{margin-top:10px;display:grid;grid-template-columns:90px 1fr;gap:6px 8px;font-size:10px}.ccMeta b{color:#5e7386}.ccPoint{margin-top:12px;background:#eaf4ff;border:1px solid #c9dff5;border-radius:8px;padding:10px 12px;color:#154d8c;font-size:11px;font-weight:800}.ccHint{font-size:9px;color:#6f8291;margin-top:7px;text-align:right}@media(max-width:760px){.ccGrid{grid-template-columns:1fr}.ccPhotos img{height:135px}}`;document.head.appendChild(s)}
function initCriteriaHover(){injectStyle();const cards=[...document.querySelectorAll('.criteria .crit')];if(cards.length<3)return;const layer=document.createElement('div');layer.className='criteriaCaseLayer';const popup=document.createElement('div');popup.className='criteriaCasePopup';document.body.append(layer,popup);let openTimer,closeTimer,current=-1;function place(card){const r=card.getBoundingClientRect();const w=Math.min(940,window.innerWidth-44);let left=Math.max(22,Math.min(window.innerWidth-w-22,r.left+r.width/2-w/2));let top=r.bottom+10;if(top+540>window.innerHeight)top=Math.max(18,r.top-500);popup.style.left=left+'px';popup.style.top=top+'px'}function render(i,card){const d=criteriaData[i],p=photoSets[d.scene];current=i;cards.forEach((c,k)=>c.classList.toggle('criteria-active',k===i));popup.innerHTML=`<div class="ccHead"><h3>${d.icon} ${d.title} <small style="font-size:11px;font-weight:700;opacity:.82">(샘플 사례)</small></h3><button class="ccClose" aria-label="닫기">×</button></div><div class="ccBody"><div class="ccGrid"><div><div class="ccBox"><h4>적용 기준</h4><ul class="ccStandards">${d.standards.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="ccEffect"><b>기대 효과</b><br>${d.effect}</div></div><div class="ccBox"><h4>현장 개선 전·후 사례</h4><div class="ccPhotos"><div class="ccPhotoWrap"><span>BEFORE</span><img src="${p.before}" alt="개선 전 실제 현장형 샘플 사진"></div><div class="ccArrow">→</div><div class="ccPhotoWrap after"><span>AFTER</span><img src="${p.after}" alt="개선 후 실제 현장형 샘플 사진"></div></div><div class="ccMeta"><b>현장</b><span>${d.site}</span><b>개선내용</b><span>${d.improve}</span><b>개선효과</b><span>${d.effect}</span></div></div></div><div class="ccPoint">핵심 포인트 : ${d.point}</div><div class="ccHint">사진은 실제 현장형 샘플이며, 향후 사내 Evidence 이미지로 교체할 수 있습니다.</div></div>`;place(card);layer.classList.add('on');popup.classList.add('on');popup.querySelector('.ccClose').onclick=hide}function show(i,card){clearTimeout(closeTimer);openTimer=setTimeout(()=>render(i,card),100)}function hide(){clearTimeout(openTimer);closeTimer=setTimeout(()=>{popup.classList.remove('on');layer.classList.remove('on');cards.forEach(c=>c.classList.remove('criteria-active'));current=-1},150)}cards.forEach((card,i)=>{card.addEventListener('mouseenter',()=>show(i,card));card.addEventListener('focusin',()=>show(i,card));card.addEventListener('click',()=>render(i,card));card.addEventListener('mouseleave',hide)});popup.addEventListener('mouseenter',()=>clearTimeout(closeTimer));popup.addEventListener('mouseleave',hide);window.addEventListener('resize',()=>{if(current>=0)place(cards[current])});window.addEventListener('scroll',()=>{if(current>=0)place(cards[current])},{passive:true});document.addEventListener('keydown',e=>{if(e.key==='Escape')hide()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initCriteriaHover);else initCriteriaHover();
})();