const CATS=['정리','정돈','청소','시각화','위험구역관리','5S고도화'];
const COLORS=['c1','c2','c3','c4','c5','c6'];
const teams=[
 {dept:'중형조립과',team:'상부조립1팀',head:38,manager:'팀장',audit:86.3},{dept:'중형조립과',team:'상부조립2팀',head:36,manager:'팀장',audit:80.7},{dept:'중형조립과',team:'메인조립팀',head:42,manager:'팀장',audit:79.3},{dept:'조립1팀',team:'하부조립팀',head:34,manager:'팀장',audit:83.3},{dept:'조립1팀',team:'Att’조립팀',head:31,manager:'팀장',audit:81.3},{dept:'대형조립과',team:'상부조립팀',head:40,manager:'팀장',audit:84.0},{dept:'대형조립과',team:'메인조립팀',head:45,manager:'팀장',audit:88.7},{dept:'대형조립과',team:'Att’조립팀',head:32,manager:'팀장',audit:91.3},{dept:'성능과',team:'성능팀',head:29,manager:'팀장',audit:78.7},{dept:'성능과',team:'T/S팀',head:27,manager:'팀장',audit:83.0},{dept:'조립2팀',team:'Front조립팀',head:44,manager:'팀장',audit:94.3},{dept:'조립2팀',team:'Rear조립팀',head:39,manager:'팀장',audit:91.3},{dept:'휠로더 초대형과',team:'메인조립팀',head:33,manager:'팀장',audit:85.0},{dept:'조립2팀',team:'옵션공정 지원팀',head:24,manager:'팀장',audit:90.7},{dept:'조립2팀',team:'초대형조립팀',head:36,manager:'팀장',audit:90.0},{dept:'제작과',team:'프레임제작팀',head:41,manager:'팀장',audit:87.7},{dept:'제작과',team:'Boom제작팀',head:35,manager:'팀장',audit:90.0},{dept:'생산지원',team:'입고·검사팀',head:26,manager:'팀장',audit:87.0},{dept:'생산지원',team:'출하팀',head:23,manager:'팀장',audit:63.0},{dept:'생산지원',team:'자재물류팀',head:30,manager:'팀장',audit:78.0}
];
const activitySummary=[
 ['조립1팀',[5,4,3,2,1,2]],['Rear조립팀',[4,2,2,3,1,1]],['가공1팀',[2,3,4,1,2,2]],['자재운영팀',[1,2,1,2,1,3]],['생산관리팀',[2,1,2,3,2,2]]
];
const productivity=[['조립1팀',3.2,1.8],['Rear조립팀',2.7,1.5],['가공1팀',2.5,1.4],['자재운영팀',2.1,1.1],['생산관리팀',1.9,.9]];
const repeatTrend=[['03월',21.4],['04월',19.8],['05월',18.1],['06월',16.7],['07월',14.9],['08월',12.5]];
const hotspots=[
 {team:'출하팀',dept:'생산지원',total:18,repeat:5,type:'정리·정돈'},
 {team:'메인조립팀',dept:'중형조립과',total:22,repeat:5,type:'정돈·시각화'},
 {team:'자재물류팀',dept:'생산지원',total:17,repeat:3,type:'정리·정돈'},
 {team:'성능팀',dept:'성능과',total:15,repeat:2,type:'청소·위험구역관리'},
 {team:'상부조립2팀',dept:'중형조립과',total:16,repeat:2,type:'정돈'}
].map(x=>({...x,rate:x.repeat/x.total*100}));
const requests=[
 {id:'5S-20260824-001',date:'2026-08-24',type:'정돈',title:'공구 보관함 라벨 부착 및 위치 지정 필요',team:'가공1팀',owner:'이민재 책임',status:'접수',priority:'높음',due:'2026-08-27'},
 {id:'5S-20260824-002',date:'2026-08-24',type:'청소',title:'바닥 절삭유 누유로 미끄럼 위험',team:'조립1팀',owner:'박성호 책임',status:'조치중',priority:'높음',due:'2026-08-26'},
 {id:'5S-20260823-003',date:'2026-08-23',type:'시각화',title:'안전수칙 및 표준작업 안내판 노후화',team:'자재운영팀',owner:'김지훈 책임',status:'접수',priority:'보통',due:'2026-08-29'},
 {id:'5S-20260823-004',date:'2026-08-23',type:'정리',title:'불필요 자재 적치로 통로 협소',team:'생산관리팀',owner:'정우진 책임',status:'접수',priority:'보통',due:'2026-08-30'},
 {id:'5S-20260822-005',date:'2026-08-22',type:'위험구역관리',title:'위험구역 경고 표지 부족',team:'T/S팀',owner:'최병길 반장',status:'조치중',priority:'높음',due:'2026-08-25'},
 {id:'5S-20260822-006',date:'2026-08-22',type:'5S고도화',title:'작업대 높낮이 조절 미흡으로 작업 불편',team:'Rear조립팀',owner:'석경원 책임',status:'완료',priority:'보통',due:'2026-08-24'},
 {id:'5S-20260821-007',date:'2026-08-21',type:'청소',title:'분진 제거 청소 미흡',team:'프레임제작팀',owner:'김태호 책임',status:'지연',priority:'높음',due:'2026-08-23'},
 {id:'5S-20260821-008',date:'2026-08-21',type:'정돈',title:'케이블 정리 미흡',team:'Boom제작팀',owner:'이창식 책임',status:'접수',priority:'보통',due:'2026-08-28'}
];
const improvements=[
 ['조립1팀','정리','불필요 치공구 제거 및 지정위치 설정'],['Rear조립팀','정돈','공구 거치대 표준화'],['가공1팀','청소','칩·오일 제거 및 바닥 청소'],['자재운영팀','시각화','자재 위치 라벨링'],['생산관리팀','정리','문서/보드 정리'],['성능팀','위험구역관리','안전 경고표지 및 라인 도색'],['T/S팀','정돈','유지보수 공구 정리함 구성'],['출하팀','청소','적재장 먼지·이물 제거'],['프레임제작팀','시각화','작업지시 보드 개선'],['메인조립팀','5S고도화','표준작업 가이드 비치'],['하부조립팀','정리','폐자재 분리수거 구역 정비'],['옵션공정 지원팀','청소','작업대 및 설비 집중청소'],['상부조립1팀','정돈','부품 박스 위치표준 개선'],['상부조립2팀','시각화','최대·최소 수량 표기'],['입고·검사팀','정리','검사대 불필요품 제거'],['자재물류팀','정돈','빈 팔레트 보관구역 지정'],['초대형조립팀','위험구역관리','보행동선 경계표시'],['Att’조립팀','5S고도화','우수사례 수평전개 보드 운영']
];
const completionByTeam=[['조립1팀',124,108],['Rear조립팀',99,84],['가공1팀',115,103],['자재운영팀',88,72],['생산관리팀',78,64]];
function $(s){return document.querySelector(s)}function $$(s){return [...document.querySelectorAll(s)]}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function switchView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function factorySvg(seed,after=false){const bg=after?'#e9f2e5':'#ece7df',line=after?'#557a54':'#876e5c',accent=after?'#5c9f68':'#bf7b3d';const bins=after?5:3;let parts='';for(let i=0;i<bins;i++){const x=22+i*34;parts+=`<rect x="${x}" y="58" width="24" height="46" rx="2" fill="${i%2?accent:line}" opacity=".78"/><rect x="${x+3}" y="63" width="18" height="5" fill="#fff" opacity=".7"/>`}return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="320" height="180"><rect width="320" height="180" fill="${bg}"/><rect y="112" width="320" height="68" fill="#cfd6da"/><path d="M0 120H320M0 145H320" stroke="#fff" stroke-width="3" opacity=".75"/><rect x="12" y="22" width="296" height="91" rx="4" fill="#d8dfe3"/><path d="M15 42H305M15 80H305" stroke="#9ba8b0" stroke-width="3"/>${parts}<rect x="218" y="52" width="72" height="55" fill="${after?'#6f8eaa':'#8b8580'}" opacity=".8"/><text x="16" y="168" font-family="Arial" font-size="18" font-weight="700" fill="#34495e">${after?'AFTER':'BEFORE'} · ${seed}</text></svg>`)}`}
function renderDashboard(){const a=$('#activityMini');if(a){a.innerHTML=activitySummary.map(([t,v])=>`<div class="team-group"><div class="team-bars-mini">${v.map((n,i)=>`<i class="${COLORS[i]}" data-v="${n}" style="height:${22+n*21}px"></i>`).join('')}</div><strong>${t}</strong></div>`).join('')}
 const p=$('#productivityMini');if(p){const mx=3.2;p.innerHTML=productivity.map(([t,x,y])=>`<div class="prod-team"><div class="prod-bars"><i class="prod-bar" data-v="${x}" style="height:${x/mx*145}px;background:#4f80a2"></i><i class="prod-bar" data-v="${y}" style="height:${y/mx*145}px;background:#72a176"></i></div><span>${t}</span></div>`).join('')}
 const audit=$('#auditCompact');if(audit){audit.innerHTML=teams.map(x=>`<div class="audit-row"><div class="audit-name"><strong>${x.team}</strong><small>${x.dept}</small></div><div class="score-track"><i style="width:${x.audit}%"></i></div><div class="audit-score ${x.audit<75?'bad':x.audit<85?'warn':''}">${x.audit.toFixed(1)}</div></div>`).join('')}
 const r=$('#repeatTrend');if(r){r.innerHTML=repeatTrend.map(([m,v])=>`<div class="repeat-col"><b>${v}%</b><i style="height:${v/25*150}px"></i><span>${m}</span></div>`).join('')}
 const h=$('#hotspotList');if(h){const mx=Math.max(...hotspots.map(x=>x.rate));h.innerHTML=hotspots.map((x,i)=>`<div class="hotspot"><div><strong>${i+1}. ${x.team}</strong><small>${x.dept} · ${x.type}</small></div><div class="hotbar"><i style="width:${x.rate/mx*100}%"></i></div><b>${x.rate.toFixed(1)}%</b></div>`).join('')}
 renderCompletion();renderImprovements('#recentImprovementGrid',12)}
function renderCompletion(){const el=$('#completionList');if(!el)return;let req=0,done=0;completionByTeam.forEach(x=>{req+=x[1];done+=x[2]});const open=req-done,rate=done/req*100;$('#cReq').textContent=req;$('#cDone').textContent=done;$('#cOpen').textContent=open;$('#cRate').textContent=rate.toFixed(1)+'%';el.innerHTML=completionByTeam.map(([t,r,d])=>{const pct=d/r*100;return `<div class="completion-row2"><span>${t}<small style="display:block;color:#8a98a8">${d}/${r}건 완료</small></span><div class="completion-track2"><i style="width:${pct}%"></i></div><b>${pct.toFixed(1)}%</b></div>`}).join('')}
function renderImprovements(sel,count=18){const el=$(sel);if(!el)return;el.innerHTML=improvements.slice(0,count).map((x,i)=>`<article class="improvement-card" data-request="${requests[i%requests.length].id}"><div class="imp-head"><strong>${i+1}. ${x[0]} · ${x[1]} 개선</strong><span>${x[2]} · 08.${String(24-(i%8)).padStart(2,'0')}</span></div><div class="photo-pair"><img src="${factorySvg(i+1,false)}" alt="Before demo"><img src="${factorySvg(i+1,true)}" alt="After demo"></div><div class="photo-caption"><span>Before</span><span>After</span></div><div class="imp-foot"><span class="demo-note">DEMO</span><span class="pill ${i%5===4?'open':'done'}">${i%5===4?'조치중':'완료'}</span></div></article>`).join('');$$('.improvement-card').forEach(c=>c.onclick=()=>openAction(c.dataset.request))}
function renderRequests(){const body=$('#requestBody');if(!body)return;body.innerHTML=requests.map(r=>`<tr><td>${r.id}</td><td>${r.date}</td><td><span class="pill">${r.type}</span></td><td>${r.title}</td><td>${r.team}</td><td>${r.owner}</td><td><span class="pill ${r.status==='완료'?'done':'open'}">${r.status}</span></td><td>${r.due}</td><td><button class="btn-sm primary" data-open="${r.id}">조치등록</button></td></tr>`).join('');$$('[data-open]').forEach(b=>b.onclick=()=>openAction(b.dataset.open))}
function openAction(id){const r=requests.find(x=>x.id===id)||requests[0];$('#modalReqId').textContent=r.id;$('#modalDate').textContent=r.date;$('#modalTeam').textContent=r.team;$('#modalOwner').textContent=r.owner;$('#modalPriority').textContent=r.priority;$('#modalStatus').textContent=r.status;$('#modalType').value=r.type;$('#modalTitle').value=r.title;$('#modalDue').value=r.due;$('#modalBefore').src=factorySvg(r.id,false);$('#modalAfter').src=factorySvg(r.id,true);$('#mailTeam').textContent=r.team;$('#mailReq').textContent=r.id;$('#actionModal').classList.add('show')}
function closeModal(){$('#actionModal').classList.remove('show')}
function renderMaster(){const org=$('#orgMasterBody');if(org)org.innerHTML=teams.map((x,i)=>`<tr><td>울산공장</td><td>${x.dept}</td><td>${x.team}</td><td>${x.head}</td><td>${x.manager}</td><td><input type="checkbox" checked></td></tr>`).join('');const mail=$('#mailMasterBody');if(mail)mail.innerHTML=teams.slice(0,10).map(x=>`<tr><td>${x.dept}</td><td>${x.team}</td><td>생산팀장</td><td>${x.team.replace(/[^가-힣A-Za-z0-9]/g,'').toLowerCase()}@company.com</td><td>개선요청 접수 즉시</td><td><input type="checkbox" checked></td></tr>`).join('')}
function renderAuditPage(){const b=$('#auditPageBody');if(b)b.innerHTML=teams.map((x,i)=>`<tr><td>${i+1}</td><td>${x.dept}</td><td>${x.team}</td><td>${[Math.round(x.audit+2),Math.round(x.audit),Math.round(x.audit-1)].join(' / ')}</td><td><b class="${x.audit<75?'bad':''}">${x.audit.toFixed(1)}</b></td><td>${x.audit<80?'집중개선':'일반관리'}</td><td><button class="btn-sm">미흡사항 보기</button></td></tr>`).join('')}
function renderRecurrence(){const b=$('#recurrenceBody');if(b)b.innerHTML=hotspots.map((x,i)=>`<tr><td>${i+1}</td><td>${x.dept}</td><td>${x.team}</td><td>${x.total}</td><td>${x.repeat}</td><td>${x.rate.toFixed(1)}%</td><td>${x.type}</td><td><button class="btn-sm">상세</button></td></tr>`).join('')}
function init(){$$('.tab').forEach(t=>t.addEventListener('click',()=>switchView(t.dataset.view)));renderDashboard();renderRequests();renderImprovements('#caseGrid',18);renderMaster();renderAuditPage();renderRecurrence();$('#modalClose')?.addEventListener('click',closeModal);$('#modalCancel')?.addEventListener('click',closeModal);$('#modalSave')?.addEventListener('click',()=>{alert('개선조치 내역이 저장되었습니다. 5S 담당자에게 완료 알림이 발송됩니다.');closeModal()});$('#actionModal')?.addEventListener('click',e=>{if(e.target.id==='actionModal')closeModal()});$('#requestSearch')?.addEventListener('input',e=>{$$('#requestBody tr').forEach(tr=>tr.style.display=tr.textContent.includes(e.target.value)?'':'none')});$('#startMonth')?.addEventListener('input',e=>{const m=Math.min(Math.max(+e.target.value||1,1),8);$('#scopeText').textContent=`2026.${String(m).padStart(2,'0')}.01 ~ 2026.08.24 누계`})}
document.addEventListener('DOMContentLoaded',init);