(()=>{'use strict';
const MAP={dashboard:[['summary','종합현황'],['analysis','성과·운영분석']],activity:[['manage','활동관리'],['analysis','실적분석']],advancement:[['judge','후보 목록'],['analysis','3조건 분석'],['detail','라인·작업장 상세'],['process','심사 프로세스'],['standard','확정·수평전개'],['map','고도화 맵'],['trend','판정기준·추이']],audit:[['draw','대상 추출'],['inspect','실시·점검 입력'],['ongoing','6개월 관리중'],['retention','종료평가']],action:[['manage','조치 목록'],['leadtime','처리기간 분석'],['master','팀장 기준정보'],['verify','효과·재발관리']]};
const CONTRACT={
 'dashboard.summary':{title:'종합현황',purpose:'울산캠퍼스 5S 운영상태를 한 화면에서 파악하고 오늘 우선 확인할 영역을 정합니다.',judge:'목표 대비 성과, 고도화 확보, Audit 대기, 미완료·기한경과·재발을 동시에 확인',next:'이상 KPI·Risk 카드를 상세근거로 Drill-down하여 담당 업무 탭으로 이동',features:['핵심 KPI','팀별 성과','Action Summary','우선순위']},
 'dashboard.analysis':{title:'성과·운영분석',purpose:'단순 실적 건수를 넘어 판정 Lead Time, 유지율, 재발률, 조치완료율 등 운영 건전성을 분석합니다.',judge:'성과 증가가 프로세스 건전성 개선과 함께 일어나는지 확인',next:'취약 지표의 원천 데이터를 확인하고 원인 업무영역에서 조치',features:['운영 KPI','월별 추이','유지율','재발·기한']},
 'activity.manage':{title:'활동관리',purpose:'현장에서 발생한 5S 개선활동을 문제·조치·증빙과 함께 누락 없이 등록하고 상태를 관리합니다.',judge:'활동 건수보다 문제와 개선내용, 생산팀, 일자, BEFORE/AFTER 증빙의 완결성을 확인',next:'미완료·미증빙 건은 보완하고 고도화 가능 건은 후보로 연결',features:['신규등록','문제·개선','BEFORE/AFTER','상태관리']},
 'activity.analysis':{title:'실적분석',purpose:'누적 활동을 생산팀·유형·기간별로 비교해 실행 편차와 고도화 전환 가능성을 찾습니다.',judge:'팀별 활동량, 완료율, 최근 추이, 후보 전환 분포의 이상치를 확인',next:'저활동·정체 팀은 실행을 촉진하고 우수 활동은 고도화 검토',features:['팀별 실적','유형 분석','월별 추이','후보 전환']},
 'advancement.judge':{title:'후보 목록',purpose:'5S 고도화 후보로 등록된 작업장 목록을 확인하고 판정 상태를 관리합니다.',judge:'후보 건수와 판정 진행 상태(판정대기·보완요청·확정)를 확인',next:'판정대기는 근거를 보완하고, 3대 조건 충족 여부는 별도 탭에서 상세 확인',features:['후보목록','판정상태','작업장별 현황']},
 'advancement.analysis':{title:'3조건 분석',purpose:'등록된 고도화 사례가 3대 조건(시각화·Green Zone·공간활용)을 얼마나 충족하는지 요약합니다.',judge:'0·1·2·3개 조건 충족 분포를 확인하되, 3/3은 공식확정이 아니라 공식심사 진입 가능 상태로 구분',next:'3/3 후보도 증빙 완결과 공식판정을 거쳐야 확정되며, 라인·작업장 상세에서 근거를 확인',features:['3대조건 요약','SCOPE·ANALYSIS']},
 'advancement.detail':{title:'라인·작업장 상세',purpose:'3대 조건 충족 현황을 생산팀·라인·작업장 단위 개별 사례로 확인합니다.',judge:'각 사례의 조건 충족수와 공식판정 상태를 별도 열로 확인해 3/3과 확정을 혼동하지 않음',next:'3/3 미확정 사례는 심사 프로세스에서 공식판정을 진행하고, 확정 Case만 확정·수평전개에서 관리',features:['라인·작업장별 상세표','충족수','공식판정']},
 'advancement.process':{title:'심사 프로세스',purpose:'등록된 5S 활동이 고도화 후보→판정→확정에 이르는 단계별로 몇 건씩 있는지 한 흐름으로 봅니다.',judge:'특정 단계에 건수가 쌓여 있지 않은지(정체) 확인',next:'정체된 단계는 후보 목록·3조건 분석에서 근거를 확인해 다음 단계로 진행',features:['심사 단계','정체 구간','단계별 건수']},
 'advancement.standard':{title:'확정·수평전개',purpose:'공식 확정된 고도화 사례를 표준화하고 유사 라인·작업장으로 재사용할 수 있게 관리합니다.',judge:'확정 자체가 아니라 적용범위, 유지상태, 재현 가능성, 수평전개 상태를 확인',next:'재현 가능한 사례는 적용 대상을 명확히 하고 유지 미흡은 Audit로 연결',features:['확정사례','표준화','적용범위','수평전개']},
 'advancement.map':{title:'고도화 맵',purpose:'팀별 고도화 수준·이탈도·공식확정 Case를 고도화/표준화 업무 안에서 확인합니다.',judge:'후보활동·공식확정·현재유지·이탈을 팀별로 비교',next:'취약 팀은 후보·3조건·심사 프로세스에서 근거를 확인',features:['Portfolio Map','공식확정 Case','유지율','이탈도']},
 'advancement.trend':{title:'판정기준·추이',purpose:'3대 고도화 판정기준과 월별 고도화 작업장 추이를 함께 확인합니다.',judge:'판정기준과 신규·유지·이탈 추이를 함께 확인',next:'이상 추이는 후보·심사·확정·수평전개 원천에서 확인',features:['3대 판정기준','고도화 작업장 추이']},
 'audit.draw':{title:'대상 추출',purpose:'Risk 가중치를 반영해 이번 Audit 대상 작업장을 무작위로 추출합니다.',judge:'추출된 대상의 팀·작업장 분포가 Risk 기준에 맞는지 확인',next:'추출 완료 후 실시·점검 입력 탭에서 실제 Audit을 진행',features:['Risk 가중 추출','대상선정']},
 'audit.inspect':{title:'실시·점검 입력',purpose:'추출된 대상에 대해 실제 Audit을 실시하고 점검항목별 결과를 입력합니다.',judge:'실시 여부, Audit 결과(적합/부적합), 점검항목별 상세 입력 완결성을 확인',next:'부적합 건은 개선조치로 연결하고, 실시일은 유지관리 D-Day로 설정',features:['Audit 실시결과','점검항목 상세입력','부적합 연계']},
 'audit.ongoing':{title:'6개월 관리중',purpose:'Audit 실시일부터 6개월 동안 개선상태가 유지되는지 진행 중인 건을 추적합니다.',judge:'관리중 건의 재발여부·유지상태와 월별 확인 누락을 점검',next:'유지미흡·재발 징후가 보이면 재조치하고, 6개월 도래 건은 종료평가 탭에서 확정',features:['6개월 추적','월별 확인','재발 징후']},
 'audit.retention':{title:'종료평가',purpose:'6개월 관리기간이 도래한 건에 대해 최종 유지 여부를 판정하고 종료평가를 완료합니다.',judge:'종료평가 대기·완료 상태와 최종 판정(적합/부적합) 결과를 확인',next:'부적합 건은 개선조치로 재연결하고, 적합 건은 관리 종료 확정',features:['종료평가','최종판정','재발 확정']},
 'action.manage':{title:'조치 목록',purpose:'Audit 및 현장 이슈에서 발생한 개선요청을 담당·기한·증빙 기반으로 끝까지 실행합니다.',judge:'기한 내 조치 여부와 BEFORE/AFTER 및 완료증빙의 충분성을 확인',next:'대기·진행·기한경과 건을 우선 Follow-up하고 완료 건은 효과검증으로 이동',features:['담당·기한','D+7~14','조치증빙','기한경과']},
 'action.leadtime':{title:'처리기간 분석',purpose:'등록부터 완료까지 개선조치의 예상·실제 해결 Lead Time을 비교해 지연 여부를 확인합니다.',judge:'계획 대비 실제 처리기간 차이가 큰 건과 지연 상태를 확인',next:'지연 건은 조치 목록에서 우선 Follow-up',features:['예상·실제 LT 비교','지연 여부']},
 'action.master':{title:'팀장 기준정보',purpose:'개선조치 알림 발송에 사용하는 생산팀장 성명·이메일 기준정보를 등록·수정합니다.',judge:'전체 16개 생산팀의 팀장 정보가 누락 없이 입력되어 있는지 확인',next:'미지정·이메일 누락 팀은 보완하고, 저장 후 조치 알림에 자동 반영',features:['팀장 기준정보','이메일 등록','Excel 일괄등록']},
 'action.verify':{title:'효과·재발관리',purpose:'완료된 개선조치가 실제 효과를 만들었는지 검증하고 같은 문제가 재발하는지 추적합니다.',judge:'완료표시와 효과확인을 분리하고 효과 미검증·재발 건을 집중 확인',next:'효과 미흡은 추가조치, 재발은 근인·대책을 재검토하여 폐쇄루프 재진입',features:['효과검증','검증대기','재발관리','폐쇄루프']}
};
const WORKFLOW={
 'activity.manage':['현장 문제·개선내용과 BEFORE/AFTER 증빙 확인','등록정보·증빙 완결 여부 판정','누락 보완 또는 고도화 후보 연결'],
 'activity.analysis':['팀·유형·기간별 실행 편차와 추이 확인','저활동·정체·우수활동 구분','실행 촉진 또는 고도화 검토'],
 'advancement.judge':['후보별 판정상태와 제출 근거 확인','판정대기·보완요청·확정 구분','근거 보완 또는 다음 심사 단계 진행'],
 'advancement.analysis':['3대 조건별 충족·미충족 분포 확인','심사 가능 수준과 부족 조건 판정','부족 조건 보완 후 상세검증'],
 'advancement.detail':['라인·작업장별 조건과 공식판정 확인','개별 사례의 조건 Gap 확인','후보 보완 또는 공식판정 연결'],
 'advancement.process':['후보→판정→확정 단계별 정체 확인','어느 단계에서 처리가 멈췄는지 판정','정체 단계 담당 업무로 즉시 연결'],
 'advancement.standard':['확정사례의 적용범위·유지상태 확인','재현·수평전개 가능 여부 판정','전개대상 지정 또는 Audit 연결'],
 'audit.draw':['Risk 기준과 추출 대상 분포 확인','이번 Audit 대상의 적정성 판단','대상 확정 후 실제 Audit 실시'],
 'audit.inspect':['점검항목·결과·부적합 근거 확인','적합/부적합 및 입력 완결성 판정','부적합 개선요청 또는 유지관리 시작'],
 'audit.ongoing':['월별 유지상태·재발징후·확인누락 점검','6개월 유지 정상/미흡 판단','재조치 또는 종료평가 준비'],
 'audit.retention':['6개월 도래 건의 최종 근거 확인','유지 적합/부적합 최종 판정','관리종료 또는 개선조치 재연결'],
 'action.manage':['담당·기한·조치내용·증빙 확인','기한경과·진행·완료 상태 판단','우선 Follow-up 또는 효과검증 이관'],
 'action.leadtime':['계획 대비 실제 처리기간 확인','병목·지연 건 판별','지연 건 조치목록 우선관리'],
 'action.master':['팀장 성명·이메일 누락/오류 확인','알림 발송 가능 상태 판단','기준정보 보완·저장'],
 'action.verify':['완료조치의 효과와 재발 여부 확인','유효/미흡/미검증·재발 판정','추가조치 또는 폐쇄루프 완료']
};
let state={area:'dashboard',sub:'summary'};const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const keyOf=(a=state.area,s=state.sub)=>`${a}.${s}`;const contract=(a=state.area,s=state.sub)=>CONTRACT[keyOf(a,s)]||CONTRACT['dashboard.summary'];
function ensure(){let bar=$('#hd20Subnav');if(!bar){bar=document.createElement('nav');bar.id='hd20Subnav';bar.className='hd20Subnav';bar.setAttribute('aria-label','세부 업무 메뉴');const anchor=$('.beginnerHint')||$('.beginnerNav');anchor?.insertAdjacentElement('afterend',bar)}return bar}
function ensurePurpose(){let el=$('#hd20PurposePanel');if(!el){el=document.createElement('section');el.id='hd20PurposePanel';el.className='hd20PurposePanel';ensure().insertAdjacentElement('afterend',el)}return el}
function enforceTopStatusOrder(area=state.area){
  if(area==='dashboard')return;
  const bar=ensure(),purpose=ensurePurpose(),metrics=$('#hd20OpsMetrics');
  if(metrics&&bar&&bar.parentNode===metrics.parentNode)bar.insertAdjacentElement('afterend',metrics);
  if(purpose&&metrics&&purpose.parentNode===metrics.parentNode)metrics.insertAdjacentElement('afterend',purpose);
  else if(purpose&&bar&&purpose.parentNode===bar.parentNode)bar.insertAdjacentElement('afterend',purpose);
}
function currentRoot(area){return area==='dashboard'?$('.app'):area==='activity'?$('#awActivity'):area==='advancement'?($('#performanceConversionAnalysis')||$('#awWorkplace')):area==='audit'?$('#awAudit'):$('#awAction')}

/* hd-22 벤치마킹: 탭마다 "사용자가 할 일 / 관리자가 관리할 것"과 핵심 버튼을 명시 */
const ROLES={
 'activity.manage':{user:'오늘 발견한 5S 문제와 개선 내용을 등록하고, BEFORE·AFTER 사진을 첨부하세요.',admin:'미완료·증빙 누락 건과 팀별 등록 편차를 확인하고, 고도화 가능 건을 후보로 연결하세요.',cta:{label:'+ 5S 신규등록',sel:'[data-aw="new"]'}},
 'activity.analysis':{user:'우리 팀의 유형별·월별 활동 추이를 보고 부족한 5S 유형을 찾으세요.',admin:'활동이 적거나 정체된 팀에 실행을 요청하고, 우수 활동은 고도화 후보로 검토하세요.'},
 'advancement.judge':{user:'우리 작업장이 후보로 올라왔는지, 판정 상태(대기·보완요청·확정)를 확인하세요.',admin:'판정대기 건의 근거를 확인해 확정 또는 보완요청을 결정하세요.'},
 'advancement.analysis':{user:'우리 작업장이 3대 조건 중 몇 개를 충족했는지 확인하세요.',admin:'1개·2개·3개 충족 분포를 보고 조건 확장이 필요한 작업장을 골라내세요.'},
 'advancement.detail':{user:'라인·작업장별 충족 조건과 공식판정 상태를 확인하세요.',admin:'충족수가 부족한 사례는 후보 목록에서, 공식판정은 확정·수평전개에서 이어서 처리하세요.'},
 'advancement.process':{user:'우리 작업장이 고도화 심사 단계 중 어디에 있는지 확인하세요.',admin:'판정대기·검토중 건의 정체 여부를 확인하고 각 단계 담당자에게 처리를 요청하세요.'},
 'advancement.standard':{user:'확정된 우수 사례를 우리 라인에 적용할 수 있는지 확인하세요.',admin:'확정 사례의 적용범위·유지상태를 관리하고 수평전개 대상을 지정하세요.'},
 'audit.draw':{user:'추출된 대상에 내 작업장이 포함됐는지 확인하고 점검을 준비하세요.',admin:'대상 추출을 실행하고, 팀·작업장 분포가 Risk 기준에 맞는지 확인하세요.',cta:{label:'🎯 대상 추출 실행',text:'대상 일괄추출'}},
 'audit.inspect':{user:'Audit을 실시한 뒤 결과(적합/부적합)와 점검항목을 입력하세요.',admin:'결과 입력이 밀린 건이 없는지 보고, 부적합 건은 개선요청으로 연결하세요.'},
 'audit.ongoing':{user:'Audit 후 6개월 동안 개선 상태가 유지되는지 월별로 확인하세요.',admin:'월별 확인이 누락되거나 재발 징후가 있는 건을 찾아 재조치하세요.'},
 'audit.retention':{user:'6개월이 지난 건의 유지 여부를 확인해 종료평가 근거를 준비하세요.',admin:'종료평가 대기 건을 유지/미흡으로 판정하고, 부적합 건은 재조치로 연결하세요.'},
 'action.manage':{user:'내 팀에 배정된 개선요청을 기한 내 조치하고 AFTER 사진을 등록하세요.',admin:'기한경과·대기 건을 먼저 확인해 독촉하고, 완료 건은 효과검증으로 넘기세요.',cta:{label:'+ 개선요청 등록',sel:'#hd20ActionRegisterBtn'}},
 'action.leadtime':{user:'내 조치가 계획보다 늦어지고 있는지 확인하세요.',admin:'계획 대비 지연이 큰 건을 찾아 조치 목록에서 우선 관리하세요.'},
 'action.master':{user:'우리 팀 팀장 이름과 이메일이 맞는지 확인하세요.',admin:'16개 팀 팀장 정보를 빠짐없이 채워야 개선요청 알림 메일이 발송됩니다.'},
 'action.verify':{user:'완료한 조치의 효과가 유지되는지 확인해 결과를 입력하세요.',admin:'효과 미검증·재발 건을 집중 확인하고, 미흡한 건은 추가조치를 요청하세요.'}
};
function runCta(c){const root=document.querySelector('.awScreen.on')||document;let b=c.sel?document.querySelector(c.sel):null;if(!b&&c.text)b=[...root.querySelectorAll('button')].find(x=>x.textContent.includes(c.text)&&!x.closest('#hd20PurposePanel'));if(b){b.scrollIntoView({block:'center'});b.click()}}
function processFlow(area,sub){
 if(area==='advancement')return '<div class="hd20ProcessFlow"><div><b>① 5S 활동 등록</b><span>문제·개선·증빙</span></div><i>→</i><div><b>② 고도화 후보</b><span>후보 지정</span></div><i>→</i><div><b>③ 3대 요건 검증</b><span>시각화·Green Zone·공간활용</span></div><i>→</i><div><b>④ 상세검증</b><span>라인·작업장 근거 확인</span></div><i>→</i><div><b>⑤ 공식 심사</b><span>충족·보완·반려 판정</span></div><i>→</i><div><b>⑥ 고도화 확정</b><span>공식 Case 확보</span></div><i>→</i><div><b>⑦ 표준화·수평전개</b><span>재현·확산</span></div><i>→</i><div><b>⑧ Audit·유지관리</b><span>6개월 유지 검증</span></div></div><div class="hd20ProcessRule"><b>심사 원칙</b><span>3대 요건은 모두 충족해야 다음 단계로 진행 · 미충족 시 보완 후 재검증 · 확정 후에도 유지요건 이탈 시 재고도화/Audit로 환류</span></div>';
 if(area==='audit')return '<div class="hd20ProcessFlow compact"><div><b>대상 추출</b><span>Risk 기반</span></div><i>→</i><div><b>Audit 실시</b><span>현장·근거 확인</span></div><i>→</i><div><b>부적합 조치</b><span>Action 연결</span></div><i>→</i><div><b>6개월 유지</b><span>월별 확인</span></div><i>→</i><div><b>종료평가</b><span>적합/부적합</span></div></div>';
 if(area==='action')return '<div class="hd20ProcessFlow compact"><div><b>개선요청</b><span>문제·근거</span></div><i>→</i><div><b>담당·기한</b><span>실행 책임</span></div><i>→</i><div><b>조치 완료</b><span>AFTER 증빙</span></div><i>→</i><div><b>효과 검증</b><span>유효성 확인</span></div><i>→</i><div><b>재발 관리</b><span>폐쇄루프</span></div></div>';
 return '';
}
function renderPurpose(area=state.area,sub=state.sub){const p=contract(area,sub),el=ensurePurpose();el.dataset.contract=keyOf(area,sub);const R=ROLES[keyOf(area,sub)]||{};const cta=R.cta,wf=WORKFLOW[keyOf(area,sub)]||[p.judge,p.judge,p.next];
  el.innerHTML=`${processFlow(area,sub)}<div class="hd20PurposeMain"><small>화면 안내 · ${MAP[area]?.find(x=>x[0]===sub)?.[1]||p.title}</small><h2>${p.title}</h2><p>${p.purpose}</p><div class="hd20RoleGrid"><div class="hd20Role user"><b>👤 사용자 · 이 화면에서 할 일</b><span>${R.user||p.judge}</span></div><div class="hd20Role admin"><b>🛠 관리자 · 이 화면에서 관리할 것</b><span>${R.admin||p.next}</span></div></div><div class="hd20WorkPath"><div><b>1. 확인</b><span>${wf[0]}</span></div><div><b>2. 판단</b><span>${wf[1]}</span></div><div><b>3. 실행</b><span>${wf[2]}</span></div></div><details class="hd20PurposeMore"><summary>판단 기준 · 다음 단계 보기</summary><div class="hd20PurposeLogic"><span><b>판단</b>${p.judge}</span><span><b>다음</b>${p.next}</span></div><div class="hd20FeatureChips">${p.features.map(x=>`<span>${x}</span>`).join('')}</div></details></div><div class="hd20PurposeSide"><div class="hd20PurposeActions">${cta?`<button type="button" class="hd20Cta" data-hd20-cta>${cta.label}</button>`:''}<button type="button" data-hd20-grid>상세 데이터 그리드</button><button type="button" data-hd20-refresh>화면 새로고침</button></div></div>`;
  el.querySelector('[data-hd20-cta]')?.addEventListener('click',()=>runCta(cta));
  el.querySelector('[data-hd20-grid]')?.addEventListener('click',()=>openGrid(area,sub));el.querySelector('[data-hd20-refresh]')?.addEventListener('click',()=>{window.HD20KPIData?.signal?.();window.dispatchEvent(new CustomEvent('hd20-refresh-requested'));apply(state.area,state.sub);renderPurpose()})}
function ensureGridModal(){let m=$('#hd20UniversalGridModal');if(m)return m;m=document.createElement('div');m.id='hd20UniversalGridModal';m.className='hd20GridModal';m.innerHTML=`<div class="hd20GridBox" role="dialog" aria-modal="true" aria-labelledby="hd20GridTitle"><div class="hd20GridHead"><div><b id="hd20GridTitle">상세 데이터</b><small id="hd20GridMeta"></small></div><button type="button" data-grid-close aria-label="닫기">×</button></div><div class="hd20GridToolbar"><input id="hd20GridSearch" type="search" placeholder="상세 데이터 검색"><button type="button" data-grid-csv>CSV 다운로드</button></div><div id="hd20GridBody" class="hd20GridBody"></div></div>`;document.body.appendChild(m);m.querySelector('[data-grid-close]').onclick=()=>m.classList.remove('on');m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('on')});document.addEventListener('keydown',e=>{if(e.key==='Escape')m.classList.remove('on')});m.querySelector('#hd20GridSearch').addEventListener('input',filterGrid);m.querySelector('[data-grid-csv]').onclick=downloadGridCsv;return m}
function visibleTable(t){if(!t||t.closest('#hd20UniversalGridModal'))return false;const cs=getComputedStyle(t);return cs.display!=='none'&&t.offsetParent!==null&&t.rows.length>0}
function tableTitle(t,i){return t.closest('.awCard,.card,.pcCard,.auditDraw,.audit6m,.auditClosedLoop')?.querySelector('.awHead,.cardHead h2,.pcHead,h3,h2,b')?.textContent?.trim()||`상세 데이터 ${i+1}`}
function collectVisible(area){const roots=area==='advancement'?[$('#performanceConversionAnalysis'),$('#awWorkplace')]:[currentRoot(area)];const seen=new Set(),sets=[];roots.filter(Boolean).forEach(root=>$$('table',root).forEach(t=>{if(!visibleTable(t)||seen.has(t))return;seen.add(t);sets.push({title:tableTitle(t,sets.length),table:t.cloneNode(true)})}));return sets}
const FALLBACK_LEGACY_TEST_IDS=new Set('DRAW-1788010755791,DRAW-1788010759290,DRAW-1788010760070,DRAW-1788010760500,DRAW-1788010760921,DRAW-1788010761360,DRAW-1788011635587,DRAW-1788011636106,DRAW-1788011636356,DRAW-1788011636538,DRAW-1788011636773,DRAW-1788011636931,DRAW-1788011637126,DRAW-1788011637396,DRAW-1788011637597,DRAW-1788011637788,DRAW-1788011637966,DRAW-1788011638138,DRAW-1788011638487,DRAW-1788011638656,DRAW-1788011638846'.split(','));
function validationMode(){const v=new URL(location.href).searchParams.get('validation');return v!=='0'&&v!=='off'}
function nonProdRow(x){if(!x||typeof x!=='object')return false;const source=String(x.source||'').trim().toLowerCase(),id=String(x.id||'').trim().toUpperCase(),sourceCaseId=String(x.sourceCaseId||'').trim().toUpperCase(),email=String(x.email||'').trim().toLowerCase();return x.isDemo===true||x.isTest===true||source==='demo-seed'||source==='e2e-fixture'||source==='web-validation-fixture'||id.startsWith('DEMO-')||id.startsWith('E2E-')||id.startsWith('VALID-')||id.includes('AUTO-DEMO-')||sourceCaseId.startsWith('DEMO-')||sourceCaseId.startsWith('E2E-')||sourceCaseId.startsWith('VALID-')||email.endsWith('@hd-hyundai-demo.co.kr')||/^teamlead\d+@example\.com$/i.test(email)||FALLBACK_LEGACY_TEST_IDS.has(id)}
function readStore(k){try{const v=JSON.parse(localStorage.getItem(k)||'[]');if(!Array.isArray(v))return[];if(k!=='hd20GMES5SAutoImproveRawV1')return v;return validationMode()?v.filter(x=>x?.source==='web-validation-fixture'):v.filter(x=>!nonProdRow(x))}catch{return[]}}
function txt(v){return String(v??'').trim()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function display(v){return v===0?'0':v===false?'false':txt(v)||'—'}
function seoulDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function doneStatus(x){return /완료|확정|종료|종결|close|done/i.test(txt(x?.status||x?.activityStatus||x?.judgeState||x?.auditState))}
function advancementType(x){const v=txt(x?.type||x?.category||x?.sType||x?.['5S구분']||x?.['활동유형']);return v==='5S 고도화'||v==='고도화'||v==='5S고도화'}
function advancementCandidate(x){if(window.HD20KPIData?.isCandidate)return window.HD20KPIData.isCandidate(x);if(!x||!advancementType(x))return false;if(x.candidate===true||x.isCandidate===true)return true;const judge=txt(x.judgeState),status=txt(x.status);if(!judge&&!status)return false;if(judge==='미확정')return /판정대기|보완요청|후보|검토|대기/.test(status);return /판정대기|보완요청|확정|후보|검토|대기/.test(judge||status)}
function advancementConfirmed(x){return window.HD20KPIData?.isConfirmed?.(x) ?? (!!x&&advancementType(x)&&x.confirmed===true&&txt(x.judgeState)==='확정')}
function advancementMaintained(x){const api=window.HD20KPIData;if(api?.isMaintained)return api.isMaintained(x);return advancementConfirmed(x)&&x?.attrition!==true&&x?.valid!==false&&!/중지|미흡|이탈|재점검|부적합|해제|실패/i.test(txt(x?.maintainState||x?.auditState||x?.status))}
function advancementAttrition(x){return advancementConfirmed(x)&&!advancementMaintained(x)}
function dueOf(x){return txt(x?.due||x?.targetDate||x?.deadline).slice(0,10)}
function actionState(x){const d=dueOf(x);if(doneStatus(x))return'완료';if(d&&d<seoulDate())return'기한경과';return d?'진행중':'기한미정'}
function effectVerified(x){if(x?.effectVerified===true)return true;const v=txt(x?.effectState??x?.effectResult);if(['미흡','부적합','무효','대기','미검증','효과확인대기','false','0','N','n'].includes(v))return false;return['유효','적합','검증완료','효과확인','효과확인완료','완료','true','1','Y','y'].includes(v)}
function recurrenceConfirmed(x){if(x?.recurrence===true)return true;const v=txt(x?.recurrenceState??x?.recurrent??x?.['재발여부']);if(['미발생','없음','미재발','false','0','N','n'].includes(v))return false;return['재발','발생','true','1','Y','y'].includes(v)}
function recurrenceKnown(x){return typeof x?.recurrence==='boolean'||!!txt(x?.recurrenceState??x?.recurrent??x?.['재발여부'])}
function closedLoopRecurrence(x){return doneStatus(x)&&effectVerified(x)&&recurrenceConfirmed(x)}
function auditId(x){return txt(x?.id||x?.drawId||x?.auditDrawId)}
function actionSourceId(x){return txt(x?.auditDrawId||x?.sourceCaseId)}
function makeTable(headers,rows){const t=document.createElement('table');t.innerHTML=`<thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(display(v))}</td>`).join('')}</tr>`).join('')}</tbody>`;return t}
function datasetFallback(area,sub){const out=[];if(area==='activity'){const rows=readStore('hd20GMES5SAutoImproveRawV1');out.push({title:sub==='manage'?'5S 활동 원천목록':'5S 활동 실적 원천목록',table:makeTable(['Activity ID','일자','유형','생산팀','작업장','등록자','문제점','개선내용','상태','BEFORE','AFTER','고도화 후보'],rows.map(x=>[x.id,x.date||x.regDate,x.type||x.category,x.team,x.workplace||x.location||x.title,x.author||x.owner,x.problem||x.issue,x.improvement||x.action||x.improve,x.status||x.judgeState,(x.before||x.evidence)?'등록':'미등록',(x.after||x.afterEvidence)?'등록':'미등록',advancementCandidate(x)?'후보':'—']))})}else if(area==='advancement'){const all=readStore('hd20GMES5SAutoImproveRawV1'),rows=sub==='standard'?all.filter(advancementConfirmed):all.filter(advancementCandidate);out.push({title:sub==='judge'?'고도화 후보·판정 원천목록':'고도화 확정·전개 원천목록',table:makeTable(['Activity ID','후보일','생산팀','작업장','판정상태','공식확정','확정일','유지상태','수평전개'],rows.map(x=>[x.id,x.date||x.regDate,x.team,x.workplace||x.location||x.title,x.judgeState||x.status,advancementConfirmed(x)?'확정':'미확정',x.confirmedAt||x.judgedAt,x.maintainState||x.auditState,(x.horizontalRollout||/전개/.test(txt(x.rolloutState)))?'전개':'—']))})}else if(area==='audit'){const rows=readStore('hd20AuditRandomDrawsV1'),actions=readStore('hd20ActionCasesV2');out.push({title:sub==='retention'?'6개월 유지관리 원천목록':'Audit 대상·실시 원천목록',table:makeTable(['Audit ID','선정일','생산팀','작업장','Audit일','결과','상태','종료평가','Action 연계','유지 Risk'],rows.map(x=>{const id=auditId(x),linked=actions.filter(a=>id&&actionSourceId(a)===id),finalState=txt(x.finalEvaluation||x.auditFinalState),risk=/미흡|부적합|실패|해제|중지/.test(finalState)||linked.some(closedLoopRecurrence);return[id,x.date||x.drawDate,x.team,x.workplace,x.auditDate,x.auditResult||x.result,x.status,x.finalEvaluation,linked.length,risk?'재발/미흡':'—']}))})}else if(area==='action'){const rows=readStore('hd20ActionCasesV2');out.push({title:sub==='manage'?'개선조치 원천목록':'효과·재발 검증 원천목록',table:makeTable(['Action ID','원천 Audit ID','등록일','생산팀','담당','문제','조치','기한','조치상태','운영상태','효과검증','재발'],rows.map(x=>[x.id,actionSourceId(x),x.registeredAt||x.date,x.team,x.owner||x.assignee,x.problem,x.action||x.improvement,dueOf(x),x.status,actionState(x),x.effectState||x.effectResult||(x.effectVerified?'검증완료':'미검증'),recurrenceKnown(x)?(recurrenceConfirmed(x)?'재발':'미발생'):'미확인']))})}return out.filter(s=>s.table.tBodies[0].rows.length)}
function openGrid(area=state.area,sub=state.sub){const m=ensureGridModal(),body=$('#hd20GridBody',m),p=contract(area,sub);let sets=collectVisible(area);if(!sets.length)sets=datasetFallback(area,sub);$('#hd20GridTitle',m).textContent=`${p.title} · 상세 데이터`;$('#hd20GridMeta',m).textContent=sets.length?`현재 업무화면/원천데이터 기준 ${sets.length}개 데이터셋`:'현재 표시 가능한 실제 데이터가 없습니다.';body.innerHTML='';if(!sets.length){body.innerHTML='<div class="hd20GridEmpty"><b>표시할 상세 데이터가 없습니다.</b><p>현재 원천데이터가 없거나 해당 업무단계에서 생성된 데이터가 없습니다. 임의 데이터를 생성하지 않습니다.</p></div>'}else sets.forEach(s=>{const sec=document.createElement('section');sec.className='hd20GridSection';const h=document.createElement('h3');h.textContent=s.title;sec.append(h,s.table);body.appendChild(sec)});$('#hd20GridSearch',m).value='';m.classList.add('on');setTimeout(()=>$('#hd20GridSearch',m)?.focus(),30)}
function filterGrid(e){const q=e.target.value.trim().toLowerCase();$$('#hd20GridBody tbody tr').forEach(tr=>tr.hidden=!!q&&!tr.textContent.toLowerCase().includes(q))}
function downloadGridCsv(){const tables=$$('#hd20GridBody table');if(!tables.length)return;const rows=[];tables.forEach((t,ti)=>{if(ti)rows.push([]);rows.push([t.closest('.hd20GridSection')?.querySelector('h3')?.textContent||'상세 데이터']);$$('tr',t).filter(tr=>!tr.hidden).forEach(tr=>rows.push($$('th,td',tr).map(x=>x.textContent.trim())))});const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`HD20_${state.area}_${state.sub}_${seoulDate()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function render(area){const bar=ensure(),items=MAP[area]||[];state.area=area;if(!items.some(x=>x[0]===state.sub))state.sub=items[0]?.[0]||'';bar.innerHTML=items.map(([k,n])=>`<button type="button" data-sub="${k}" class="${k===state.sub?'on':''}">${n}</button>`).join('');$$('button',bar).forEach(b=>b.onclick=()=>select(area,b.dataset.sub));renderPurpose(area,state.sub);requestAnimationFrame(()=>apply(area,state.sub))}
function ensureAdvancementUiStyle(){if(document.getElementById('hd20AdvancementUiStyle'))return;const s=document.createElement('style');s.id='hd20AdvancementUiStyle';s.textContent=`.hd20AdvFunnel{display:flex;align-items:stretch;gap:8px;margin:12px 0 14px}.hd20AdvFunnel>div{position:relative;flex:1;min-width:0;border:1px solid #dbe5ec;background:#f8fbfd;padding:11px 18px 11px 12px;border-radius:10px}.hd20AdvFunnel small{display:block;color:#5c7284;font-weight:800;font-size:11px}.hd20AdvFunnel b{display:block;color:#173b55;font-size:22px;margin-top:3px}.hd20AdvFunnel i{position:absolute;right:-9px;top:50%;transform:translateY(-50%);z-index:2;color:#7890a2;font-style:normal;font-weight:900}.hd20AdvFunnel .loss{border-color:#e8c6c6;background:#fff7f7}.hd20AdvFunnel .loss b{color:#a33b3b}@media(max-width:760px){.hd20AdvFunnel{display:grid;grid-template-columns:1fr 1fr}.hd20AdvFunnel i{display:none}}.hd20JudgeReadiness,.hd20CriteriaMiss,.hd20ProcQueues,.hd20StandardSummary,.hd20DetailHotspots{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin:12px 0 14px}.hd20JudgeReadiness>div,.hd20CriteriaMiss>div,.hd20ProcQueue,.hd20StandardSummary>div,.hd20DetailHotspots>div{border:1px solid #dbe5ec;background:#fff;border-radius:10px;padding:12px 14px;min-width:0}.hd20JudgeReadiness small,.hd20CriteriaMiss small,.hd20ProcQueue small,.hd20StandardSummary small,.hd20DetailHotspots small{display:block;color:#5c7284;font-size:12px;font-weight:800}.hd20JudgeReadiness b,.hd20CriteriaMiss b,.hd20ProcQueue b,.hd20StandardSummary b,.hd20DetailHotspots b{display:block;margin-top:4px;color:#173b55;font-size:20px}.hd20ProcQueue span,.hd20DetailHotspots span{display:block;margin-top:5px;color:#607789;font-size:12px;line-height:1.45}.hd20JudgeReadiness .risk,.hd20CriteriaMiss .risk,.hd20ProcQueue.risk,.hd20StandardSummary .risk,.hd20DetailHotspots .risk{border-color:#e8c6c6;background:#fff7f7}.hd20JudgeReadiness .risk b,.hd20CriteriaMiss .risk b,.hd20ProcQueue.risk b,.hd20StandardSummary .risk b,.hd20DetailHotspots .risk b{color:#a33b3b}@media(max-width:760px){.hd20JudgeReadiness,.hd20CriteriaMiss,.hd20ProcQueues,.hd20StandardSummary,.hd20DetailHotspots{grid-template-columns:1fr 1fr}}.hd20AdvancementTrend{grid-template-columns:minmax(300px,.85fr) minmax(420px,1.35fr)!important;align-items:stretch}.hd20AdvancementTrend>.card{height:auto!important;min-height:0!important}.hd20AdvancementTrend .criteria{height:auto!important;min-height:0!important}.hd20AdvancementTrend .crit{padding:14px 10px!important}.hd20AdvancementTrend .trendBox{min-height:280px}@media(max-width:900px){.hd20AdvancementTrend{grid-template-columns:1fr!important}}`;document.head.appendChild(s)}
function show(el,on){if(el)el.classList.toggle('hd20SubHidden',!on)}function showAll(root,sel='.awCard'){if(root)$$(sel,root).forEach(el=>show(el,true))}
function applyDashboard(sub){const cards=$('.cards'),main=$('.mainGrid'),bottom=$('.bottomGrid'),priority=$('#hd20DashboardPriority'),bridge=$('#hd20OperationalBridge');if(sub==='summary'){show(cards,true);show(main,true);show(priority,true);show(bridge,false);show(bottom,false);if(main){show(main.children?.[0],true);show($('.sideStack',main),true)}}else{show(cards,false);show(main,true);show(priority,true);show(bridge,true);show(bottom,true);if(main){show(main.children?.[0],false);show($('.sideStack',main),true)}}}
function applyActivity(sub){const root=$('#awActivity');if(!root)return;root.dataset.subview=sub;showAll(root);show($('.awGrid',root),true);const form=$('.awRegisterFormCard',root);if(form)show(form,sub==='manage');
  /* 실적분석: 등록/가져오기 도구를 숨기고 팀별 분석 콘텐츠 위주로 구성해
     활동관리(등록·조회)와 실질적으로 구분되도록 함(내용 삭제가 아니라
     서브탭별 표시 범위 재구성). */
  const isAnalysis=sub==='analysis';
  show($('.awFlow',root),!isAnalysis);
  show($('.awActions',root),!isAnalysis);
  show(document.getElementById('hd20ActivityExcelImport'),!isAnalysis);
  show(document.getElementById('hd20ImportAnalysis'),!isAnalysis);
  /* 팀별 5S 유형 활동현황 차트는 분석 화면(실적분석)에만 표시 —
     활동관리(등록·조회)와 같은 차트가 두 탭에 중복 노출되던 문제 정리 */
  show($('.adcCard',root),isAnalysis);
}
function ensureAdvAnalysis(){
 let host=$('#hd20AdvAnalysisOperational');if(host)return host;host=document.createElement('section');host.id='hd20AdvAnalysisOperational';host.className='pcPanel hd20AdvAnalysisOperational';const root=$('#performanceConversionAnalysis');(root?.querySelector('.pcGrid')||root)?.appendChild(host);return host
}
function advCriteriaFlags(x){const ok=v=>v===true||/^(Y|YES|충족|적합)$/i.test(txt(v));if(Array.isArray(x?.criteriaMatched)){const s=new Set(x.criteriaMatched);return ['시각화·형적관리','인간공학적 Green Zone','정량축소·정위치 변경을 통한 공간 활용'].map(k=>s.has(k))}return [ok(x?.visualization??x?.criteriaVisual),ok(x?.greenZone??x?.criteriaGreen),ok(x?.spaceUtilization??x?.criteriaSpace)]}
function renderAdvAnalysis(){
 const host=ensureAdvAnalysis();if(!host)return;const rows=readStore('hd20GMES5SAutoImproveRawV1').filter(advancementCandidate);const names=['시각화·형적관리','Green Zone','공간활용'];
 const miss=names.map((name,i)=>({name,count:rows.filter(x=>!advCriteriaFlags(x)[i]).length}));const dist=[0,1,2,3].map(n=>({n,count:rows.filter(x=>advCriteriaCount(x)===n).length}));const ready=rows.filter(x=>advCriteriaCount(x)===3&&!advancementConfirmed(x)).length,confirmed=rows.filter(advancementConfirmed).length,lost=rows.filter(advancementAttrition);
 const teams={};rows.forEach(x=>{const k=txt(x.team)||'미지정';teams[k]??={rows:[],lost:0};teams[k].rows.push(x);if(lost.includes(x))teams[k].lost++});
 const teamRows=Object.entries(teams).map(([team,v])=>{const m=names.map((_,i)=>v.rows.filter(x=>!advCriteriaFlags(x)[i]).length);return{team,total:v.rows.length,m,lost:v.lost}}).sort((a,b)=>(b.m.reduce((s,n)=>s+n,0)+b.lost)-(a.m.reduce((s,n)=>s+n,0)+a.lost));
 host.innerHTML=`<div class="pcPanelHead">3대 요건 미충족 집중도 <small>3/3은 공식확정이 아니라 공식심사 진입 가능 상태입니다.</small></div><div class="hd20CriteriaMiss">${dist.map(x=>`<div class="${x.n<3?'risk':''}"><small>${x.n}/3 충족</small><b>${x.count}건</b></div>`).join('')}<div><small>3/3 미확정</small><b>${ready}건</b></div><div><small>공식확정</small><b>${confirmed}건</b></div><div class="risk"><small>확정 후 유지이탈</small><b>${lost.length}건</b></div></div><div class="hd20CriteriaMiss">${miss.map(x=>`<div><small>${x.name} 미충족</small><b>${x.count}건</b></div>`).join('')}</div><div class="pcTableWrap"><table class="pcTable"><thead><tr><th>생산팀</th><th>후보</th><th>시각화 미충족</th><th>Green Zone 미충족</th><th>공간활용 미충족</th><th>확정 후 이탈</th></tr></thead><tbody>${teamRows.map(r=>`<tr><td>${esc(r.team)}</td><td>${r.total}</td><td>${r.m[0]}</td><td>${r.m[1]}</td><td>${r.m[2]}</td><td><b>${r.lost}</b></td></tr>`).join('')||'<tr><td colspan="6">현재 고도화 후보 데이터가 없습니다.</td></tr>'}</tbody></table></div>`
}
function ensureAdvDetail(){
 let host=$('#hd20AdvDetailOperational');if(host)return host;
 host=document.createElement('section');host.id='hd20AdvDetailOperational';host.className='pcPanel hd20AdvDetailOperational';
 const root=$('#performanceConversionAnalysis');(root?.querySelector('.pcGrid')||root)?.appendChild(host);return host
}
function advCriteriaCount(x){if(Array.isArray(x?.criteriaMatched))return Math.max(0,Math.min(3,x.criteriaMatched.length));const n=Number(x?.criteriaMatched);if(Number.isFinite(n))return Math.max(0,Math.min(3,n));const a=[x?.visualization??x?.criteriaVisual,x?.greenZone??x?.criteriaGreen,x?.spaceUtilization??x?.criteriaSpace];return a.filter(v=>v===true||/^(Y|YES|충족|적합)$/i.test(txt(v))).length}
function advLine(x){return txt(x?.line||x?.lineName||x?.productionLine||x?.['라인'])||'미분류/라인 매핑 필요'}
function advGap(x){const n=advCriteriaCount(x);if(n>=3)return '3대 요건 충족';const gaps=[];const checks=[['시각화·형적관리',x?.visualization??x?.criteriaVisual],['Green Zone',x?.greenZone??x?.criteriaGreen],['공간활용',x?.spaceUtilization??x?.criteriaSpace]];checks.forEach(([k,v])=>{if(!(v===true||/^(Y|YES|충족|적합)$/i.test(txt(v))))gaps.push(k)});return gaps.length?gaps.join(' · '):`${3-n}개 요건 보완 필요`}
function renderAdvDetail(){
 const host=ensureAdvDetail();if(!host)return;const rows=readStore('hd20GMES5SAutoImproveRawV1').filter(advancementCandidate);
 const teamGap={};rows.forEach(x=>{const team=txt(x.team)||'미지정',flags=advCriteriaFlags(x);teamGap[team]??={total:0,visual:0,green:0,space:0,lost:0,ready:0};const t=teamGap[team];t.total++;if(!flags[0])t.visual++;if(!flags[1])t.green++;if(!flags[2])t.space++;if(advancementAttrition(x))t.lost++;if(advCriteriaCount(x)===3&&!advancementConfirmed(x))t.ready++});const hotspots=Object.entries(teamGap).map(([team,v])=>({team,...v,gap:v.visual+v.green+v.space})).sort((a,b)=>(b.gap+b.lost*2)-(a.gap+a.lost*2)).slice(0,5);const body=rows.slice().sort((a,b)=>(advancementAttrition(b)?1:0)-(advancementAttrition(a)?1:0)||advCriteriaCount(a)-advCriteriaCount(b)).map(x=>{const lost=advancementAttrition(x);const reason=lost?(txt(x.attritionReason)||txt(x.maintainState||x.auditState||x.status)||'유지 이탈'):'—';return `<tr><td>${esc(txt(x.team)||'—')}</td><td>${esc(advLine(x))}</td><td>${esc(txt(x.workplace||x.title)||'—')}</td><td><b>${advCriteriaCount(x)}/3</b></td><td>${esc(advGap(x))}</td><td>${esc(txt(x.judgeState||x.status)||'미확정')}</td><td>${esc(reason)}</td></tr>`}).join('');
 host.innerHTML=`<div class="pcPanelHead">라인·작업장별 심사 Gap · 이탈 상세 <small>원천데이터 기준 · 미분류 라인은 임의 추정하지 않음</small></div><div class="hd20DetailHotspots">${hotspots.map((r,i)=>`<div class="${r.lost?'risk':''}"><small>${i+1}. ${esc(r.team)}</small><b>Gap ${r.gap} · 이탈 ${r.lost}</b><span>시각화 ${r.visual} / Green ${r.green} / 공간 ${r.space} · 3/3 미확정 ${r.ready}</span></div>`).join('')||'<div><small>집중관리 대상</small><b>데이터 없음</b></div>'}</div><div class="pcTableWrap"><table class="pcTable"><thead><tr><th>생산팀</th><th>라인</th><th>작업장/활동</th><th>충족</th><th>보완 필요 요건</th><th>공식판정</th><th>확정 후 이탈사유</th></tr></thead><tbody>${body||'<tr><td colspan="7">현재 고도화 후보 상세 데이터가 없습니다.</td></tr>'}</tbody></table></div>`
}
function ensureAdvJudge(){
 let host=$('#hd20AdvJudgeOperational');if(host)return host;host=document.createElement('section');host.id='hd20AdvJudgeOperational';host.className='pcPanel hd20AdvJudgeOperational';const root=$('#performanceConversionAnalysis');(root?.querySelector('.pcGrid')||root)?.prepend(host);return host
}
function advEvidenceGap(x){const gaps=[];if(!txt(x?.problem))gaps.push('문제정의');if(!txt(x?.improvement||x?.action))gaps.push('개선내용');if(!txt(x?.before))gaps.push('BEFORE');if(!txt(x?.after))gaps.push('AFTER');return gaps}
function renderAdvJudge(){
 const host=ensureAdvJudge();if(!host)return;const rows=readStore('hd20GMES5SAutoImproveRawV1').filter(advancementCandidate).filter(x=>!advancementConfirmed(x));
 const body=rows.slice().sort((a,b)=>advEvidenceGap(b).length-advEvidenceGap(a).length||advCriteriaCount(a)-advCriteriaCount(b)).map(x=>{const eg=advEvidenceGap(x),n=advCriteriaCount(x),s=txt(x?.judgeState||x?.status)||'판정대기';const next=eg.length?'증빙 보완':n<3?'3대 요건 보완':'공식판정 진행';return `<tr><td>${esc(txt(x.team)||'—')}</td><td>${esc(advLine(x))}</td><td>${esc(txt(x.workplace||x.title)||'—')}</td><td>${esc(s)}</td><td>${n}/3</td><td>${esc(eg.length?eg.join(' · '):'완결')}</td><td>${esc(n<3?advGap(x):'3대 요건 충족')}</td><td><b>${esc(next)}</b></td></tr>`}).join('');
 const evidenceGap=rows.filter(x=>advEvidenceGap(x).length).length,criteriaGap=rows.filter(x=>advCriteriaCount(x)<3).length,ready=rows.filter(x=>!advEvidenceGap(x).length&&advCriteriaCount(x)>=3).length;const bothGap=rows.filter(x=>advEvidenceGap(x).length&&advCriteriaCount(x)<3).length,evidenceOnly=rows.filter(x=>advEvidenceGap(x).length&&advCriteriaCount(x)>=3).length,criteriaOnly=rows.filter(x=>!advEvidenceGap(x).length&&advCriteriaCount(x)<3).length;
 host.innerHTML=`<div class="pcPanelHead">후보 심사 준비도 · 보완 우선순위 <small>후보 등록 이후 실제로 무엇이 부족해 판정으로 못 넘어가는지 확인</small></div><div class="hd20JudgeReadiness"><div><small>미확정 후보</small><b>${rows.length}건</b></div><div class="risk"><small>증빙+요건 동시 Gap</small><b>${bothGap}건</b></div><div class="risk"><small>증빙만 보완</small><b>${evidenceOnly}건</b></div><div class="risk"><small>요건만 보완</small><b>${criteriaOnly}건</b></div><div><small>공식판정 준비완료</small><b>${ready}건</b></div></div><div class="pcTableWrap"><table class="pcTable"><thead><tr><th>생산팀</th><th>라인</th><th>후보 Case</th><th>판정상태</th><th>요건</th><th>증빙 Gap</th><th>요건 Gap</th><th>다음 조치</th></tr></thead><tbody>${body||'<tr><td colspan="8">현재 미확정 고도화 후보가 없습니다.</td></tr>'}</tbody></table></div>`
}
function ensureAdvProcess(){
 let host=$('#hd20AdvProcessOperational');if(host)return host;host=document.createElement('section');host.id='hd20AdvProcessOperational';host.className='pcPanel hd20AdvProcessOperational';const root=$('#performanceConversionAnalysis');(root?.querySelector('.pcGrid')||root)?.appendChild(host);return host
}
function advProcessState(x){
 const n=advCriteriaCount(x),s=txt(x?.judgeState||x?.status),confirmed=advancementConfirmed(x),evidenceGap=advEvidenceGap(x).length;
 if(confirmed)return advancementAttrition(x)?'유지 이탈':'확정·전개';
 if(evidenceGap)return '후보 지정';
 if(/보완/.test(s)||n<3)return '요건 보완';
 if(n>=3)return '공식심사 대기';
 return '후보 지정'
}
function advProcessReason(x,state){
 if(state==='유지 이탈')return txt(x?.attritionReason)||'확정 후 유지요건 재점검 필요';
 if(state==='요건 보완')return advGap(x);
 if(state==='공식심사 대기')return '3대 요건 충족 · 공식판정 대기';
 if(state==='확정·전개')return '공식확정 · 표준화/수평전개 및 유지관리';
 return advEvidenceGap(x).length?'후보 증빙 보완: '+advEvidenceGap(x).join(' · '):'후보 근거 및 3대 요건 검증 필요'
}
function renderAdvProcess(){
 const host=ensureAdvProcess();if(!host)return;const rows=readStore('hd20GMES5SAutoImproveRawV1').filter(advancementCandidate);
 const states=['후보 지정','요건 보완','공식심사 대기','확정·전개','유지 이탈'];const grouped=Object.fromEntries(states.map(s=>[s,[]]));rows.forEach(x=>{const s=advProcessState(x);(grouped[s]||(grouped[s]=[])).push(x)});
 const confirmed=rows.filter(advancementConfirmed),maintained=confirmed.filter(advancementMaintained),lost=confirmed.filter(advancementAttrition),candidateOnly=rows.filter(x=>!advancementConfirmed(x));const ready=candidateOnly.filter(x=>advCriteriaCount(x)===3&&!advEvidenceGap(x).length),gap=candidateOnly.filter(x=>advCriteriaCount(x)<3||advEvidenceGap(x).length);const cards=[['전체 후보',rows.length,'등록된 고도화 활동'],['보완·검증',gap.length,'증빙 또는 3대 요건 Gap'],['3/3 심사대기',ready.length,'공식확정 전 단계'],['공식확정',confirmed.length,'judgeState=확정'],['현재 유지',maintained.length,'확정 후 유지 중'],['확정 후 이탈',lost.length,'유지 실패·재점검']].map(([s,n,d])=>`<div class="hd20ProcQueue ${s==='보완·검증'||s==='확정 후 이탈'?'risk':''}"><small>${s}</small><b>${n}건</b><span>${d}</span></div>`).join('');const funnel=`<div class="hd20AdvFunnel">${[['후보',rows.length],['보완/검증',gap.length],['3/3 심사대기',ready.length],['공식확정',confirmed.length],['현재 유지',maintained.length]].map(([k,n],i)=>`<div><small>${k}</small><b>${n}</b>${i<4?'<i>→</i>':''}</div>`).join('')}<div class="loss"><small>확정 후 이탈</small><b>${lost.length}</b></div></div>`;
 const queue=rows.filter(x=>['후보 지정','요건 보완','공식심사 대기','유지 이탈'].includes(advProcessState(x))).sort((a,b)=>advCriteriaCount(a)-advCriteriaCount(b));
 const body=queue.map(x=>{const s=advProcessState(x);return `<tr><td>${esc(txt(x.team)||'—')}</td><td>${esc(advLine(x))}</td><td>${esc(txt(x.workplace||x.title)||'—')}</td><td><b>${esc(s)}</b></td><td>${advCriteriaCount(x)}/3</td><td>${esc(advProcessReason(x,s))}</td><td>${esc(s==='유지 이탈'?'Audit/재고도화':s==='후보 지정'?'증빙 보완 후 요건검증':s==='요건 보완'?'요건 보완 후 재검증':'공식판정 진행')}</td></tr>`}).join('');
 host.innerHTML=`<div class="pcPanelHead">고도화 심사 Funnel · 정체/이탈 관리 <small>3/3과 공식확정을 분리하고, 확정 후 유지·이탈까지 한 흐름으로 관리합니다.</small></div>${funnel}<div class="hd20ProcQueues">${cards}</div><div class="pcTableWrap"><table class="pcTable"><thead><tr><th>생산팀</th><th>라인</th><th>작업장/활동</th><th>현재 단계</th><th>요건</th><th>정체·환류 사유</th><th>다음 조치</th></tr></thead><tbody>${body||'<tr><td colspan="7">현재 정체·환류 대상 Case가 없습니다.</td></tr>'}</tbody></table></div>`
}
function ensureAdvStandard(){
 let host=$('#hd20AdvStandardOperational');if(host)return host;host=document.createElement('section');host.id='hd20AdvStandardOperational';host.className='pcPanel hd20AdvStandardOperational';const root=$('#performanceConversionAnalysis');(root?.querySelector('.pcGrid')||root)?.appendChild(host);return host
}
function advScope(x){return txt(x?.rolloutScope||x?.applyScope||x?.scope||x?.horizontalDeployment||x?.['적용범위'])||'미설정'}
function advStandardState(x){return txt(x?.standardState||x?.standardizationState||x?.standardized||x?.['표준화상태'])||'미설정'}
function advRolloutState(x){return txt(x?.rolloutState||x?.deploymentState||x?.['수평전개상태'])||'미설정'}
function renderAdvStandard(){
 const host=ensureAdvStandard();if(!host)return;const all=readStore('hd20GMES5SAutoImproveRawV1');const rows=all.filter(advancementConfirmed);
 const lost=rows.filter(advancementAttrition);const maintained=rows.filter(advancementMaintained);const maintainRate=rows.length?Math.round(maintained.length/rows.length*100):0;
 const unsetScope=rows.filter(x=>advScope(x)==='미설정').length,unsetStd=rows.filter(x=>advStandardState(x)==='미설정').length,unsetRoll=rows.filter(x=>advRolloutState(x)==='미설정').length;
 const body=rows.slice().sort((a,b)=>(lost.includes(a)?-1:1)).map(x=>{const isLost=lost.includes(x);return `<tr><td>${esc(txt(x.team)||'—')}</td><td>${esc(advLine(x))}</td><td>${esc(txt(x.workplace||x.title)||'—')}</td><td>${esc(advStandardState(x))}</td><td>${esc(advScope(x))}</td><td>${esc(advRolloutState(x))}</td><td>${esc(isLost?(txt(x.attritionReason)||'유지 이탈'):(txt(x.maintainState)||'유지'))}</td><td><b>${isLost?'Audit/재고도화':(advScope(x)==='미설정'||advRolloutState(x)==='미설정'?'전개정보 보완':'유지관리')}</b></td></tr>`}).join('');
 host.innerHTML=`<div class="pcPanelHead">확정 Case 표준화 · 수평전개 · 유지관리 <small>확정이 끝이 아니라 재현·전개·유지까지 관리</small></div><div class="hd20StandardSummary"><div><small>공식확정</small><b>${rows.length}건</b></div><div><small>현재 유지</small><b>${maintained.length}건</b></div><div><small>유지율</small><b>${maintainRate}%</b></div><div class="risk"><small>유지 이탈</small><b>${lost.length}건</b></div><div><small>적용범위 미설정</small><b>${unsetScope}건</b></div><div><small>표준화 미설정</small><b>${unsetStd}건</b></div><div><small>수평전개 미설정</small><b>${unsetRoll}건</b></div></div><div class="pcTableWrap"><table class="pcTable"><thead><tr><th>생산팀</th><th>라인</th><th>확정 Case</th><th>표준화</th><th>적용범위</th><th>수평전개</th><th>유지상태</th><th>다음 관리</th></tr></thead><tbody>${body||'<tr><td colspan="8">현재 공식확정 Case가 없습니다.</td></tr>'}</tbody></table></div>`
}
function applyAdvancement(sub){const conversion=$('#performanceConversionAnalysis'),work=$('#awWorkplace'),judge=ensureAdvJudge(),analysis=ensureAdvAnalysis(),detail=ensureAdvDetail(),process=ensureAdvProcess(),standard=ensureAdvStandard(),map=document.getElementById('hd20MaturityMapTab'),trend=document.querySelector('.bottomGrid');document.querySelector('.app')?.classList.add('awFocused');if(conversion){conversion.classList.add('on');show(conversion,true);conversion.classList.toggle('hd20AdvancementStandard',sub==='standard');conversion.dataset.subview=sub}if(work){work.classList.add('on');show(work,true);work.dataset.subview=sub;showAll(work);show($('.awFlow',work),true);show($('.awGrid',work),true)}if(judge){if(sub==='judge')renderAdvJudge();show(judge,sub==='judge')}if(analysis){if(sub==='analysis')renderAdvAnalysis();show(analysis,sub==='analysis')}if(detail){if(sub==='detail')renderAdvDetail();show(detail,sub==='detail')}if(process){if(sub==='process')renderAdvProcess();show(process,sub==='process')}if(standard){if(sub==='standard')renderAdvStandard();show(standard,sub==='standard')}if(map){if(sub==='map'){window.HD20_MATURITY_MAP_TAB?.show?.();map.hidden=false}else{window.HD20_MATURITY_MAP_TAB?.hide?.();map.hidden=true}show(map,sub==='map')}if(trend){show(trend,sub==='trend');trend.querySelectorAll(':scope > .card').forEach(x=>show(x,sub==='trend'));if(sub==='trend'){trend.classList.add('hd20AdvancementTrend');const criteria=trend.querySelector('.criteria')?.closest('.card'),chart=trend.querySelector('.trendBox')?.closest('.card');if(criteria)criteria.querySelector('.cardHead h2').innerHTML='고도화 공식 판정기준 <small>3대 요건 모두 충족 필요</small>';if(chart)chart.querySelector('.cardHead h2').textContent='공식확정·유지 추이'}}else trend?.classList.remove('hd20AdvancementTrend')}
function applyAudit(sub){const root=$('#awAudit');if(!root)return;root.dataset.subview=sub;showAll(root);show($('.awFlow',root),true);show($('.awAuditLane',root),true);const draw=$('.auditDraw',root),batch=$('#hd20AuditBatchExecution',root),closed=$('.auditClosedLoop',root),ongoing=$('.audit6m',root),closeEval=document.getElementById('hd20AuditCloseEvaluation');show(draw,sub==='draw');show(batch,sub==='draw');show(closed,sub==='inspect');show(ongoing,sub==='ongoing');show(closeEval,sub==='retention')}
function ensureActionVerify(root){let host=$('#hd20ActionVerifyStatus',root);if(!host){host=document.createElement('section');host.id='hd20ActionVerifyStatus';host.className='awCard';const anchor=$('.awKpis',root)||$('.awFlow',root)||$('.amHeroNote',root)||$('.awHero',root);anchor?.insertAdjacentElement('afterend',host)}return host}
function renderActionVerify(root){const host=ensureActionVerify(root);if(!host)return;const rows=readStore('hd20ActionCasesV2'),done=rows.filter(doneStatus),verified=done.filter(effectVerified),pendingVerify=done.filter(x=>!effectVerified(x)),recurrence=verified.filter(recurrenceConfirmed);host.innerHTML=`<div class="awHead"><div><b>효과·재발 검증현황</b><small>실제 개선조치 데이터 기준 · 미입력 결과는 임의 생성하지 않습니다.</small></div></div><div class="awKpis"><div><small>전체 개선요청</small><b>${rows.length}건</b></div><div><small>조치 진행·대기</small><b>${rows.length-done.length}건</b></div></div><div class="awHint" style="margin-top:10px">${pendingVerify.length?`완료 ${done.length}건 중 효과검증 미입력 ${pendingVerify.length}건은 <b>검증 대기</b> 상태입니다.`:done.length?'완료된 개선조치는 모두 효과검증 결과가 입력되어 있습니다.':'완료된 개선조치가 없어 효과검증 대상이 없습니다.'}</div>`}
function applyAction(sub){const root=$('#awAction');if(!root)return;root.dataset.subview=sub;showAll(root);show($('.awFlow',root),true);show($('.awKpis',root),true);const form=$('.amRegisterFormCard',root),verify=ensureActionVerify(root);show(form,sub==='manage');if(sub==='verify'){renderActionVerify(root);show(verify,true)}else{show(verify,false)}
  /* '+ 개선요청 등록' 등 신규 등록 액션은 '조치 목록'(manage)에서만
     의미가 있어, 다른 3개 서브탭(처리기간분석/팀장기준정보/효과재발
     관리)에서는 숨김. 내용 삭제가 아니라 서브탭별 표시 범위 재구성. */
  show($('.awActions',root),sub==='manage');
}
function apply(area,sub){enforceTopStatusOrder(area);try{document.querySelector('.app')?.setAttribute('data-hd-view',area+'.'+sub)}catch(e){}
  if(area==='dashboard')applyDashboard(sub);else if(area==='activity')applyActivity(sub);else if(area==='advancement')applyAdvancement(sub);else if(area==='audit')applyAudit(sub);else if(area==='action')applyAction(sub);window.dispatchEvent(new CustomEvent('hd20-subtab-changed',{detail:{area,sub}}))}
function select(area,sub){state={area,sub};$$('button',ensure()).forEach(b=>b.classList.toggle('on',b.dataset.sub===sub));apply(area,sub);renderPurpose(area,sub);
  try{const u=new URL(location.href);if(u.searchParams.get('area')===area)u.searchParams.set('sub',sub);history.replaceState(null,'',u)}catch{}}
function syncArea(area){
  if(window.__HD20_RESTORE_SUB&&MAP[area]?.some(([k])=>k===window.__HD20_RESTORE_SUB)){
    const restoreSub=window.__HD20_RESTORE_SUB;window.__HD20_RESTORE_SUB=null;
    state.sub=restoreSub;state.area=area;const bar=ensure(),items=MAP[area]||[];
    bar.innerHTML=items.map(([k,n])=>`<button type="button" data-sub="${k}" class="${k===restoreSub?'on':''}">${n}</button>`).join('');
    $$('button',bar).forEach(b=>b.onclick=()=>select(area,b.dataset.sub));
    ensure().style.removeProperty('display');ensurePurpose().style.removeProperty('display');
    renderPurpose(area,restoreSub);requestAnimationFrame(()=>apply(area,restoreSub));return;
  }
  if(!MAP[area]){
    /* '통합기준정보' 등 이 서브탭 체계를 모르는 새 영역으로 이동한 경우: 안내 카드·서브탭 바가 이전 영역
       내용을 그대로 보여준 채 남아있던 결함 → 둘 다 숨김(빈 화면으로 진입시 잔상 없음) */
    [ensure(),ensurePurpose(),$('#hd20OpsMetrics')].forEach(el=>el&&el.style.setProperty('display','none','important'));return
  }
  [ensure(),ensurePurpose(),$('#hd20OpsMetrics')].forEach(el=>el&&el.style.removeProperty('display'));
  state.sub=(MAP[area]||[])[0]?.[0]||'';state.area=area;const bar=ensure(),items=MAP[area]||[];bar.innerHTML=items.map(([k,n])=>`<button type="button" data-sub="${k}" class="${k===state.sub?'on':''}">${n}</button>`).join('');$$('button',bar).forEach(b=>b.onclick=()=>select(area,b.dataset.sub));renderPurpose(area,state.sub);requestAnimationFrame(()=>apply(area,state.sub))}
function bindMain(){const nav=$('.beginnerNav');if(!nav)return;nav.addEventListener('click',e=>{const b=e.target.closest('button[data-key]');if(!b)return;setTimeout(()=>syncArea(b.dataset.key),60)});window.addEventListener('hd20-nav-area-changed',e=>{const area=e.detail?.area;if(!MAP[area]){[ensure(),ensurePurpose(),$('#hd20OpsMetrics')].forEach(el=>el&&el.style.setProperty('display','none','important'));return}if(state.area===area&&$('#hd20PurposePanel'))return;setTimeout(()=>syncArea(area),0)})}
function refreshActiveAdvancement(){if(state.area!=='advancement')return;if(state.sub==='analysis')renderAdvAnalysis();else if(state.sub==='detail')renderAdvDetail();else if(state.sub==='process')renderAdvProcess();else if(state.sub==='standard')renderAdvStandard();else if(state.sub==='map')window.HD20_MATURITY_MAP_TAB?.render?.();else if(state.sub==='judge')renderAdvJudge()}
function boot(){ensureAdvancementUiStyle();ensure();ensureGridModal();bindMain();window.addEventListener('hd20-action-updated',()=>{if(state.area==='action'&&state.sub==='verify')renderActionVerify($('#awAction'))});['hd20-kpi-source-updated','hd20-gmes-5s-imported','hd20-gmes-5s-judged','hd20-refresh-requested'].forEach(e=>window.addEventListener(e,()=>setTimeout(refreshActiveAdvancement,0)));setTimeout(()=>render(window.HD20_NAV?.active?.()||'dashboard'),120)}
window.HD20_SUBNAV={render,select,state:()=>({...state}),map:MAP,contracts:CONTRACT,purpose:CONTRACT,contractMap:(area)=>area?{[area]:MAP[area]}:MAP,contractPurpose:(area)=>area?Object.fromEntries(Object.entries(CONTRACT).filter(([k])=>k.startsWith(area+'.'))):CONTRACT,openGrid:()=>openGrid(state.area,state.sub),advancementType,advancementCandidate,advancementConfirmed};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();