(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORES={activity:'hd20GMES5SAutoImproveRawV1',audit:'hd20AuditRandomDrawsV1',action:'hd20ActionCasesV2'};
const PAGE_SIZE=40;
function read(k){try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function txt(v){return String(v??'').trim()}
function esc(v){return txt(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function num(v){return Number.isFinite(Number(v))?Number(v):0}
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function state(){return window.HD20_SUBNAV?.state?.()||{area:window.HD20_NAV?.active?.()||'dashboard',sub:'summary'}}
function status(x){return txt(x?.status||x?.activityStatus||x?.judgeState||x?.auditState)}
function isDone(x){return /완료|확정|종료|종결|close|done/i.test(status(x))}
function overdue(x){const d=txt(x?.due||x?.targetDate||x?.deadline).slice(0,10);return !!d&&!isDone(x)&&d<today()}
function effectVerified(x){if(x?.effectVerified===true)return true;const v=txt(x?.effectState??x?.effectResult);if(['미흡','부적합','무효','대기','미검증','효과확인대기','false','0','N','n'].includes(v))return false;return['유효','적합','검증완료','효과확인','효과확인완료','완료','true','1','Y','y'].includes(v)}
function recurrence(x){if(x?.recurrence===true)return true;const v=txt(x?.recurrenceState??x?.recurrent??x?.['재발여부']);if(['미발생','없음','미재발','false','0','N','n'].includes(v))return false;return['재발','발생','true','1','Y','y'].includes(v)}
function closedLoopRecurrence(x){return isDone(x)&&effectVerified(x)&&recurrence(x)}
function auditId(x){return txt(x?.id||x?.drawId||x?.auditDrawId)}
function actionSourceId(x){return txt(x?.auditDrawId||x?.sourceCaseId)}
function metrics(area,sub){const acts=read(STORES.activity),audits=read(STORES.audit),actions=read(STORES.action);const candidates=acts.filter(x=>x.candidate||x.isCandidate||txt(x.type)==='5S 고도화'),confirmed=candidates.filter(x=>x.confirmed===true||/확정/.test(status(x))),doneActions=actions.filter(isDone),linkedActions=actions.filter(a=>{const id=actionSourceId(a);return !!id&&audits.some(d=>auditId(d)===id)});const map={
'dashboard.summary':[['5S 활동',acts.length,'건'],['고도화 후보',candidates.length,'건'],['Audit 대기',audits.filter(x=>!x.auditDate).length,'건'],['기한경과',actions.filter(overdue).length,'건']],
'dashboard.analysis':[['완료 활동',acts.filter(isDone).length,'건'],['공식확정',confirmed.length,'건'],['6개월 관리',audits.filter(x=>x.auditDate&&!x.finalEvaluation).length,'건'],['재발',actions.filter(closedLoopRecurrence).length,'건']],
'activity.manage':[['전체 활동',acts.length,'건'],['완료/확정',acts.filter(isDone).length,'건'],['진행/등록',acts.filter(x=>!isDone(x)).length,'건'],['고도화 후보',candidates.length,'건']],
'activity.analysis':[['전체 활동',acts.length,'건'],['생산팀',new Set(acts.map(x=>txt(x.team)).filter(Boolean)).size,'팀'],['고도화 전환',candidates.length,'건'],['최근 30일',acts.filter(x=>{const d=new Date(x.date||x.regDate||x.createdAt||0);return Number.isFinite(d.getTime())&&Date.now()-d.getTime()<=2592e6}).length,'건']],
'advancement.judge':[['후보',candidates.length,'건'],['판정대기',candidates.filter(x=>!(/확정/.test(status(x))||x.confirmed===true)).length,'건'],['공식확정',confirmed.length,'건'],['3조건 충족',candidates.filter(x=>window.HD20MaturityConditionAnalysis?.criteriaState?.(x)?.count===3).length,'건']],
'advancement.standard':[['공식확정',confirmed.length,'건'],['현재 유지',confirmed.filter(x=>!/미흡|부적합|중지|해제|실패/.test(txt(x.maintainState||x.auditState||x.status))).length,'건'],['유지 미흡',confirmed.filter(x=>/미흡|부적합|중지|해제|실패/.test(txt(x.maintainState||x.auditState||x.status))||x.valid===false).length,'건'],['수평전개',confirmed.filter(x=>x.horizontalRollout||/전개/.test(txt(x.rolloutState))).length,'건']],
'audit.audit':[['Audit 원천',audits.length,'건'],['실시 대기',audits.filter(x=>!x.auditDate).length,'건'],['Audit 완료',audits.filter(x=>x.auditDate).length,'건'],['부적합',audits.filter(x=>/부적합|미흡|NG|fail/i.test(txt(x.auditResult||x.result||x.status))).length,'건']],
'audit.retention':[['관리중',audits.filter(x=>x.auditDate&&!x.finalEvaluation).length,'건'],['종료평가',audits.filter(x=>x.finalEvaluation).length,'건'],['재발/미흡',audits.filter(x=>/재발|미흡|부적합/.test(txt(x.status||x.maintainState||x.finalEvaluation))).length,'건'],['Action 연계',linkedActions.length,'건']],
'action.manage':[['전체 개선요청',actions.length,'건'],['진행/대기',actions.filter(x=>!isDone(x)).length,'건'],['완료',doneActions.length,'건'],['기한경과',actions.filter(overdue).length,'건']],
'action.verify':[['검증 대상',doneActions.length,'건'],['효과검증 완료',doneActions.filter(effectVerified).length,'건'],['검증대기',doneActions.filter(x=>!effectVerified(x)).length,'건'],['재발',doneActions.filter(x=>effectVerified(x)&&recurrence(x)).length,'건']]};return map[`${area}.${sub}`]||map['dashboard.summary']}
function renderMetrics(){const s=state(),anchor=$('#hd20PurposePanel');if(!anchor)return;let bar=$('#hd20OpsMetrics');if(!bar){bar=document.createElement('section');bar.id='hd20OpsMetrics';bar.className='hd20OpsMetrics';anchor.insertAdjacentElement('afterend',bar)}bar.dataset.contract=`${s.area}.${s.sub}`;bar.innerHTML=metrics(s.area,s.sub).map(([n,v,u],i)=>`<button type="button" data-metric="${i}"><small>${esc(n)}</small><b>${esc(v)}<em>${esc(u)}</em></b></button>`).join('');$$('button',bar).forEach((b,i)=>b.onclick=()=>metricDrill(s.area,s.sub,i));ensureTraceButton(s.area)}
function metricDrill(area,sub,index){const routes={dashboard:[['activity','analysis'],['advancement','judge'],['audit','audit'],['action','manage']],activity:[['activity','manage'],['activity','analysis'],['advancement','judge'],['activity','analysis']],advancement:[['advancement','judge'],['advancement','judge'],['advancement','standard'],['advancement','standard']],audit:[['audit','audit'],['audit','audit'],['audit','retention'],['action','manage']],action:[['action','manage'],['action','manage'],['action','verify'],['action','verify']]};const r=(routes[area]||[])[index]||[area,sub];go(r[0],r[1],{openGrid:true})}
function go(area,sub,opts={}){window.HD20_NAV?.go?.(area);setTimeout(()=>{window.HD20_SUBNAV?.select?.(area,sub);const url=new URL(location.href);url.searchParams.set('tab',area);url.searchParams.set('sub',sub);if(opts.q)url.searchParams.set('q',opts.q);else url.searchParams.delete('q');history.replaceState(null,'',url);setTimeout(()=>{if(opts.openGrid){window.HD20_SUBNAV?.openGrid?.();setTimeout(()=>{const q=$('#hd20GridSearch');if(q&&opts.q){q.value=opts.q;q.dispatchEvent(new Event('input',{bubbles:true}))}},80)}},80)},80)}
function bindDashboardRoutes(){const kp=$$('.cards .kpi');const kpr=[['activity','analysis'],['advancement','judge'],['advancement','standard'],['advancement','standard'],['audit','retention']];kp.forEach((el,i)=>{if(!kpr[i])return;el.classList.add('hd20DeepLink');el.setAttribute('role','button');el.tabIndex=0;const fn=()=>go(kpr[i][0],kpr[i][1],{openGrid:true});el.onclick=fn;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fn()}}});const ar=$$('.actionList .actionRow'),rr=[['audit','audit'],['action','manage'],['action','manage'],['action','verify']];ar.forEach((el,i)=>{if(!rr[i])return;el.classList.add('hd20DeepLink');el.setAttribute('role','button');el.tabIndex=0;el.onclick=()=>go(rr[i][0],rr[i][1],{openGrid:true})})}
function ensureGridChrome(){const m=$('#hd20UniversalGridModal');if(!m||!m.classList.contains('on'))return;m.dataset.opsV2='1';$$('.hd20GridSection',m).forEach(sec=>{if(!sec.querySelector('.hd20GridControls'))enhanceSection(sec)})}
function enhanceSection(sec){const table=$('table',sec);if(!table)return;let ctl=$('.hd20GridControls',sec);if(!ctl){ctl=document.createElement('div');ctl.className='hd20GridControls';ctl.innerHTML='<span class="hd20GridCount"></span><label>행 표시<select><option>20</option><option selected>40</option><option>80</option><option value="9999">전체</option></select></label><button type="button">필터 초기화</button>';sec.querySelector('h3')?.insertAdjacentElement('afterend',ctl)}const rows=$$('tbody tr',table),heads=$$('thead th',table);rows.forEach((tr,i)=>{tr.dataset.baseIndex=i;tr.tabIndex=0;tr.classList.add('hd20GridRow');tr.onclick=e=>{if(e.target.closest('a,button,input,select'))return;openRowDetail(sec,table,tr)}});heads.forEach((th,i)=>{th.classList.add('hd20Sortable');th.tabIndex=0;th.title='클릭하여 정렬';th.onclick=()=>sortTable(table,i,th);th.onkeydown=e=>{if(e.key==='Enter')sortTable(table,i,th)}});ctl.querySelector('select').onchange=()=>paginate(sec);ctl.querySelector('button').onclick=()=>{const q=$('#hd20GridSearch');if(q){q.value='';q.dispatchEvent(new Event('input',{bubbles:true}))}rows.forEach(r=>r.dataset.searchHidden='0');paginate(sec)};paginate(sec)}
function sortTable(table,col,th){const body=table.tBodies[0],rows=$$('tr',body),asc=th.dataset.sort!=='asc';$$('th',th.parentElement).forEach(h=>{delete h.dataset.sort;h.classList.remove('sortAsc','sortDesc')});th.dataset.sort=asc?'asc':'desc';th.classList.add(asc?'sortAsc':'sortDesc');rows.sort((a,b)=>{const av=txt(a.cells[col]?.textContent),bv=txt(b.cells[col]?.textContent),an=Number(av.replace(/[,%건곳팀]/g,'')),bn=Number(bv.replace(/[,%건곳팀]/g,''));const c=Number.isFinite(an)&&Number.isFinite(bn)?an-bn:av.localeCompare(bv,'ko',{numeric:true});return asc?c:-c}).forEach(r=>body.appendChild(r));paginate(table.closest('.hd20GridSection'))}
function paginate(sec){const table=$('table',sec),ctl=$('.hd20GridControls',sec);if(!table||!ctl)return;const size=num(ctl.querySelector('select').value)||PAGE_SIZE,rows=$$('tbody tr',table),visible=rows.filter(r=>r.dataset.searchHidden!=='1');rows.forEach(r=>r.hidden=true);visible.slice(0,size).forEach(r=>r.hidden=false);ctl.querySelector('.hd20GridCount').textContent=`${visible.length}건${visible.length>size?` · 상위 ${size}건 표시`:''}`}
function syncSearch(){const m=$('#hd20UniversalGridModal');if(!m)return;const q=txt($('#hd20GridSearch',m)?.value).toLowerCase();$$('.hd20GridSection',m).forEach(sec=>{$$('tbody tr',sec).forEach(r=>r.dataset.searchHidden=q&&!r.textContent.toLowerCase().includes(q)?'1':'0');paginate(sec)})}
function ensureRowDetail(){let p=$('#hd20RowDetail');if(p)return p;p=document.createElement('div');p.id='hd20RowDetail';p.className='hd20RowDetail';p.innerHTML='<div class="hd20RowDetailBox"><div class="hd20RowDetailHead"><div><b>행 상세정보</b><small>선택한 원천데이터</small></div><button type="button" aria-label="닫기">×</button></div><div class="hd20RowDetailBody"></div></div>';document.body.appendChild(p);p.querySelector('button').onclick=()=>p.classList.remove('on');p.onclick=e=>{if(e.target===p)p.classList.remove('on')};return p}
function openRowDetail(sec,table,tr){const p=ensureRowDetail(),heads=$$('thead th',table),cells=$$('td',tr);$('.hd20RowDetailHead b',p).textContent=sec.querySelector('h3')?.textContent||'행 상세정보';$('.hd20RowDetailBody',p).innerHTML=`<div class="hd20RowFields">${cells.map((c,i)=>`<div><small>${esc(txt(heads[i]?.textContent)||`항목 ${i+1}`)}</small><b>${esc(txt(c.textContent)||'—')}</b></div>`).join('')}</div>${traceForRow(cells.map(c=>txt(c.textContent)))}`;p.classList.add('on')}
function traceForRow(vals){const actions=read(STORES.action),joined=actions.filter(a=>{const id=txt(a.id),source=actionSourceId(a);return !!id&&vals.includes(id)||!!source&&vals.includes(source)});if(!joined.length)return'';return `<div class="hd20InlineTrace"><b>정확 ID 연계 개선조치 ${joined.length}건</b>${joined.slice(0,5).map(a=>`<span>${esc(txt(a.id)||'Action')} · ${esc(txt(a.status)||'상태없음')} · ${effectVerified(a)&&isDone(a)?'효과검증완료':'효과검증대기'} · ${closedLoopRecurrence(a)?'재발':'재발없음/미확인'}</span>`).join('')}</div>`}
function ensureTraceButton(area){const panel=$('#hd20PurposePanel .hd20PurposeActions');if(!panel)return;let b=$('[data-hd20-trace]',panel);if(area!=='audit'&&area!=='action'){b?.remove();return}if(!b){b=document.createElement('button');b.type='button';b.dataset.hd20Trace='1';b.textContent='연계 흐름';panel.appendChild(b)}b.onclick=openTraceability}
function openTraceability(){let m=$('#hd20TraceModal');if(!m){m=document.createElement('div');m.id='hd20TraceModal';m.className='hd20TraceModal';m.innerHTML='<div class="hd20TraceBox"><div class="hd20GridHead"><div><b>Audit → 개선조치 → 효과·재발 Traceability</b><small>Audit ID / Action ID 정확 키 매칭</small></div><button type="button" aria-label="닫기">×</button></div><div class="hd20TraceBody"></div></div>';document.body.appendChild(m);m.querySelector('button').onclick=()=>m.classList.remove('on');m.onclick=e=>{if(e.target===m)m.classList.remove('on')}}const audits=read(STORES.audit),actions=read(STORES.action),rows=[],linked=[];audits.forEach(a=>{const id=auditId(a),matches=actions.filter(x=>id&&actionSourceId(x)===id);linked.push(...matches);if(matches.length)matches.forEach(x=>rows.push([id,txt(a.team)||'—',txt(a.auditDate)||'미실시',txt(a.auditResult||a.result)||'—',txt(x.id)||'—',txt(x.status)||'—',isDone(x)&&effectVerified(x)?'검증완료':'검증대기',closedLoopRecurrence(x)?'재발':'—']));else rows.push([id||'—',txt(a.team)||'—',txt(a.auditDate)||'미실시',txt(a.auditResult||a.result)||'—','미연계','—','—','—'])});const body=$('.hd20TraceBody',m),uniqueLinked=[...new Map(linked.map(x=>[txt(x.id)||actionSourceId(x),x])).values()];body.innerHTML=rows.length?`<div class="hd20TraceSummary"><b>Audit ${audits.length}건</b><b>Action 연계 ${uniqueLinked.length}건</b><b>효과검증 완료 ${uniqueLinked.filter(x=>isDone(x)&&effectVerified(x)).length}건</b><b>재발 ${uniqueLinked.filter(closedLoopRecurrence).length}건</b></div><div class="hd20TraceTable"><table><thead><tr><th>Audit ID</th><th>생산팀</th><th>Audit일</th><th>Audit결과</th><th>Action ID</th><th>조치상태</th><th>효과검증</th><th>재발</th></tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="hd20GridEmpty"><b>연결 가능한 실제 Audit 데이터가 없습니다.</b><p>임의 연결이나 문자열 유사도 추정은 수행하지 않습니다.</p></div>';m.classList.add('on')}
function bootDeepLink(){const u=new URL(location.href),area=u.searchParams.get('tab'),sub=u.searchParams.get('sub'),q=u.searchParams.get('q');if(area&&sub)setTimeout(()=>go(area,sub,{openGrid:!!q,q:q||''}),300)}
function bind(){bindDashboardRoutes();renderMetrics();window.addEventListener('hd20-subtab-changed',()=>setTimeout(renderMetrics,30));['hd20-action-updated','hd20-gmes-5s-imported','storage','hd20-refresh-requested'].forEach(ev=>window.addEventListener(ev,()=>setTimeout(renderMetrics,50)));document.addEventListener('input',e=>{if(e.target?.id==='hd20GridSearch')setTimeout(syncSearch,0)},true);const mo=new MutationObserver(()=>ensureGridChrome());mo.observe(document.documentElement,{subtree:true,attributes:true,attributeFilter:['class'],childList:true});bootDeepLink();setInterval(()=>{if($('#hd20UniversalGridModal.on'))ensureGridChrome()},700)}
window.HD20_OPS_V2={go,openTraceability,renderMetrics,metrics,effectVerified,recurrence,closedLoopRecurrence,overdue,isDone};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',bind,{once:true}):bind();
})();