(()=>{'use strict';
const MAP={dashboard:[['summary','종합현황'],['analysis','성과·운영분석']],activity:[['manage','활동관리'],['analysis','실적분석']],advancement:[['judge','후보 목록'],['analysis','3조건 분석'],['detail','라인·작업장 상세'],['standard','확정·수평전개']],audit:[['draw','대상 추출'],['inspect','실시·점검 입력'],['ongoing','6개월 관리중'],['retention','종료평가']],action:[['manage','조치 목록'],['leadtime','처리기간 분석'],['master','팀장 기준정보'],['verify','효과·재발관리']]};
const CONTRACT={
 'dashboard.summary':{title:'종합현황',purpose:'울산캠퍼스 5S 운영상태를 한 화면에서 파악하고 오늘 우선 확인할 영역을 정합니다.',judge:'목표 대비 성과, 고도화 확보, Audit 대기, 미완료·기한경과·재발을 동시에 확인',next:'이상 KPI·Risk 카드를 상세근거로 Drill-down하여 담당 업무 탭으로 이동',features:['핵심 KPI','팀별 성과','Action Summary','우선순위']},
 'dashboard.analysis':{title:'성과·운영분석',purpose:'단순 실적 건수를 넘어 판정 Lead Time, 유지율, 재발률, 조치완료율 등 운영 건전성을 분석합니다.',judge:'성과 증가가 프로세스 건전성 개선과 함께 일어나는지 확인',next:'취약 지표의 원천 데이터를 확인하고 원인 업무영역에서 조치',features:['운영 KPI','월별 추이','유지율','재발·기한']},
 'activity.manage':{title:'활동관리',purpose:'현장에서 발생한 5S 개선활동을 문제·조치·증빙과 함께 누락 없이 등록하고 상태를 관리합니다.',judge:'활동 건수보다 문제와 개선내용, 생산팀, 일자, BEFORE/AFTER 증빙의 완결성을 확인',next:'미완료·미증빙 건은 보완하고 고도화 가능 건은 후보로 연결',features:['신규등록','문제·개선','BEFORE/AFTER','상태관리']},
 'activity.analysis':{title:'실적분석',purpose:'누적 활동을 생산팀·유형·기간별로 비교해 실행 편차와 고도화 전환 가능성을 찾습니다.',judge:'팀별 활동량, 완료율, 최근 추이, 후보 전환 분포의 이상치를 확인',next:'저활동·정체 팀은 실행을 촉진하고 우수 활동은 고도화 검토',features:['팀별 실적','유형 분석','월별 추이','후보 전환']},
 'advancement.judge':{title:'후보 목록',purpose:'5S 고도화 후보로 등록된 작업장 목록을 확인하고 판정 상태를 관리합니다.',judge:'후보 건수와 판정 진행 상태(판정대기·보완요청·확정)를 확인',next:'판정대기는 근거를 보완하고, 3대 조건 충족 여부는 별도 탭에서 상세 확인',features:['후보목록','판정상태','작업장별 현황']},
 'advancement.analysis':{title:'3조건 분석',purpose:'등록된 고도화 사례가 3대 조건(시각화·Green Zone·공간활용)을 얼마나 충족하는지 요약합니다.',judge:'1개/2개 이상/3개 모두 충족 구간별 건수와 SCOPE·ANALYSIS 현황을 확인',next:'구간별 분포를 확인한 뒤 라인·작업장별 상세는 별도 탭에서 확인',features:['3대조건 요약','SCOPE·ANALYSIS']},
 'advancement.detail':{title:'라인·작업장 상세',purpose:'3대 조건 충족 현황을 생산팀·라인·작업장 단위 개별 사례로 확인합니다.',judge:'각 사례의 조건 충족수와 공식판정 상태를 개별 행 단위로 확인',next:'조건 확장이 필요한 사례는 후보 목록에서, 공식판정은 확정·수평전개에서 이어서 관리',features:['라인·작업장별 상세표','충족수','공식판정']},
 'advancement.standard':{title:'확정·수평전개',purpose:'공식 확정된 고도화 사례를 표준화하고 유사 라인·작업장으로 재사용할 수 있게 관리합니다.',judge:'확정 자체가 아니라 적용범위, 유지상태, 재현 가능성, 수평전개 상태를 확인',next:'재현 가능한 사례는 적용 대상을 명확히 하고 유지 미흡은 Audit로 연결',features:['확정사례','표준화','적용범위','수평전개']},
 'audit.draw':{title:'대상 추출',purpose:'Risk 가중치를 반영해 이번 Audit 대상 작업장을 무작위로 추출합니다.',judge:'추출된 대상의 팀·작업장 분포가 Risk 기준에 맞는지 확인',next:'추출 완료 후 실시·점검 입력 탭에서 실제 Audit을 진행',features:['Risk 가중 추출','대상선정']},
 'audit.inspect':{title:'실시·점검 입력',purpose:'추출된 대상에 대해 실제 Audit을 실시하고 점검항목별 결과를 입력합니다.',judge:'실시 여부, Audit 결과(적합/부적합), 점검항목별 상세 입력 완결성을 확인',next:'부적합 건은 개선조치로 연결하고, 실시일은 유지관리 D-Day로 설정',features:['Audit 실시결과','점검항목 상세입력','부적합 연계']},
 'audit.ongoing':{title:'6개월 관리중',purpose:'Audit 실시일부터 6개월 동안 개선상태가 유지되는지 진행 중인 건을 추적합니다.',judge:'관리중 건의 재발여부·유지상태와 월별 확인 누락을 점검',next:'유지미흡·재발 징후가 보이면 재조치하고, 6개월 도래 건은 종료평가 탭에서 확정',features:['6개월 추적','월별 확인','재발 징후']},
 'audit.retention':{title:'종료평가',purpose:'6개월 관리기간이 도래한 건에 대해 최종 유지 여부를 판정하고 종료평가를 완료합니다.',judge:'종료평가 대기·완료 상태와 최종 판정(적합/부적합) 결과를 확인',next:'부적합 건은 개선조치로 재연결하고, 적합 건은 관리 종료 확정',features:['종료평가','최종판정','재발 확정']},
 'action.manage':{title:'조치 목록',purpose:'Audit 및 현장 이슈에서 발생한 개선요청을 담당·기한·증빙 기반으로 끝까지 실행합니다.',judge:'기한 내 조치 여부와 BEFORE/AFTER 및 완료증빙의 충분성을 확인',next:'대기·진행·기한경과 건을 우선 Follow-up하고 완료 건은 효과검증으로 이동',features:['담당·기한','D+7~14','조치증빙','기한경과']},
 'action.leadtime':{title:'처리기간 분석',purpose:'등록부터 완료까지 개선조치의 예상·실제 해결 Lead Time을 비교해 지연 여부를 확인합니다.',judge:'계획 대비 실제 처리기간 차이가 큰 건과 지연 상태를 확인',next:'지연 건은 조치 목록에서 우선 Follow-up',features:['예상·실제 LT 비교','지연 여부']},
 'action.master':{title:'팀장 기준정보',purpose:'개선조치 알림 발송에 사용하는 생산팀장 성명·이메일 기준정보를 등록·수정합니다.',judge:'전체 16개 생산팀의 팀장 정보가 누락 없이 입력되어 있는지 확인',next:'미지정·이메일 누락 팀은 보완하고, 저장 후 조치 알림에 자동 반영',features:['팀장 기준정보','이메일 등록','Excel 일괄등록']},
 'action.verify':{title:'효과·재발관리',purpose:'완료된 개선조치가 실제 효과를 만들었는지 검증하고 같은 문제가 재발하는지 추적합니다.',judge:'완료표시와 효과확인을 분리하고 효과 미검증·재발 건을 집중 확인',next:'효과 미흡은 추가조치, 재발은 근인·대책을 재검토하여 폐쇄루프 재진입',features:['효과검증','검증대기','재발관리','폐쇄루프']}
};
let state={area:'dashboard',sub:'summary'};const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const keyOf=(a=state.area,s=state.sub)=>`${a}.${s}`;const contract=(a=state.area,s=state.sub)=>CONTRACT[keyOf(a,s)]||CONTRACT['dashboard.summary'];
function ensure(){let bar=$('#hd20Subnav');if(!bar){bar=document.createElement('nav');bar.id='hd20Subnav';bar.className='hd20Subnav';bar.setAttribute('aria-label','세부 업무 메뉴');const anchor=$('.beginnerHint')||$('.beginnerNav');anchor?.insertAdjacentElement('afterend',bar)}return bar}
function ensurePurpose(){let el=$('#hd20PurposePanel');if(!el){el=document.createElement('section');el.id='hd20PurposePanel';el.className='hd20PurposePanel';ensure().insertAdjacentElement('afterend',el)}return el}
function currentRoot(area){return area==='dashboard'?$('.app'):area==='activity'?$('#awActivity'):area==='advancement'?($('#performanceConversionAnalysis')||$('#awWorkplace')):area==='audit'?$('#awAudit'):$('#awAction')}
function renderPurpose(area=state.area,sub=state.sub){const p=contract(area,sub),el=ensurePurpose();el.dataset.contract=keyOf(area,sub);el.innerHTML=`<div class="hd20PurposeMain"><small>화면 안내 · ${MAP[area]?.find(x=>x[0]===sub)?.[1]||p.title}</small><h2>${p.title}</h2><p>${p.purpose}</p><div class="hd20PurposeLogic"><span><b>판단</b>${p.judge}</span><span><b>다음</b>${p.next}</span></div></div><div class="hd20PurposeSide"><div class="hd20FeatureChips">${p.features.map(x=>`<span>${x}</span>`).join('')}</div><div class="hd20PurposeActions"><button type="button" data-hd20-grid>상세 데이터 그리드</button><button type="button" data-hd20-refresh>화면 새로고침</button></div></div>`;el.querySelector('[data-hd20-grid]')?.addEventListener('click',()=>openGrid(area,sub));el.querySelector('[data-hd20-refresh]')?.addEventListener('click',()=>{window.HD20KPIData?.signal?.();window.dispatchEvent(new CustomEvent('hd20-refresh-requested'));apply(state.area,state.sub);renderPurpose()})}
function ensureGridModal(){let m=$('#hd20UniversalGridModal');if(m)return m;m=document.createElement('div');m.id='hd20UniversalGridModal';m.className='hd20GridModal';m.innerHTML=`<div class="hd20GridBox" role="dialog" aria-modal="true" aria-labelledby="hd20GridTitle"><div class="hd20GridHead"><div><b id="hd20GridTitle">상세 데이터</b><small id="hd20GridMeta"></small></div><button type="button" data-grid-close aria-label="닫기">×</button></div><div class="hd20GridToolbar"><input id="hd20GridSearch" type="search" placeholder="상세 데이터 검색"><button type="button" data-grid-csv>CSV 다운로드</button></div><div id="hd20GridBody" class="hd20GridBody"></div></div>`;document.body.appendChild(m);m.querySelector('[data-grid-close]').onclick=()=>m.classList.remove('on');m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('on')});document.addEventListener('keydown',e=>{if(e.key==='Escape')m.classList.remove('on')});m.querySelector('#hd20GridSearch').addEventListener('input',filterGrid);m.querySelector('[data-grid-csv]').onclick=downloadGridCsv;return m}
function visibleTable(t){if(!t||t.closest('#hd20UniversalGridModal'))return false;const cs=getComputedStyle(t);return cs.display!=='none'&&t.offsetParent!==null&&t.rows.length>0}
function tableTitle(t,i){return t.closest('.awCard,.card,.pcCard,.auditDraw,.audit6m,.auditClosedLoop')?.querySelector('.awHead,.cardHead h2,.pcHead,h3,h2,b')?.textContent?.trim()||`상세 데이터 ${i+1}`}
function collectVisible(area){const roots=area==='advancement'?[$('#performanceConversionAnalysis'),$('#awWorkplace')]:[currentRoot(area)];const seen=new Set(),sets=[];roots.filter(Boolean).forEach(root=>$$('table',root).forEach(t=>{if(!visibleTable(t)||seen.has(t))return;seen.add(t);sets.push({title:tableTitle(t,sets.length),table:t.cloneNode(true)})}));return sets}
function readStore(k){try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v:[]}catch{return[]}}
function txt(v){return String(v??'').trim()}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function display(v){return v===0?'0':v===false?'false':txt(v)||'—'}
function seoulDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function doneStatus(x){return /완료|확정|종료|종결|close|done/i.test(txt(x?.status||x?.activityStatus||x?.judgeState||x?.auditState))}
function advancementType(x){const v=txt(x?.type||x?.category||x?.sType||x?.['5S구분']||x?.['활동유형']);return v==='5S 고도화'||v==='고도화'||v==='5S고도화'}
function advancementCandidate(x){if(!x||!advancementType(x))return false;if(x.candidate===true||x.isCandidate===true)return true;const s=txt(x.judgeState||x.status);if(!s||s==='미확정')return false;return /판정대기|보완요청|확정|후보|검토|대기/.test(s)}
function advancementConfirmed(x){return !!x&&advancementType(x)&&x.confirmed===true&&txt(x.judgeState)==='확정'}
function dueOf(x){return txt(x?.due||x?.targetDate||x?.deadline).slice(0,10)}
function actionState(x){const d=dueOf(x);if(doneStatus(x))return'완료';if(d&&d<seoulDate())return'기한경과';return d?'진행중':'기한미정'}
function effectVerified(x){if(x?.effectVerified===true)return true;const v=txt(x?.effectState??x?.effectResult);if(['미흡','부적합','무효','대기','미검증','효과확인대기','false','0','N','n'].includes(v))return false;return['유효','적합','검증완료','효과확인','효과확인완료','완료','true','1','Y','y'].includes(v)}
function recurrenceConfirmed(x){if(x?.recurrence===true)return true;const v=txt(x?.recurrenceState??x?.recurrent??x?.['재발여부']);if(['미발생','없음','미재발','false','0','N','n'].includes(v))return false;return['재발','발생','true','1','Y','y'].includes(v)}
function recurrenceKnown(x){return typeof x?.recurrence==='boolean'||!!txt(x?.recurrenceState??x?.recurrent??x?.['재발여부'])}
function closedLoopRecurrence(x){return doneStatus(x)&&effectVerified(x)&&recurrenceConfirmed(x)}
function auditId(x){return txt(x?.id||x?.drawId||x?.auditDrawId)}
function actionSourceId(x){return txt(x?.auditDrawId||x?.sourceCaseId)}
function makeTable(headers,rows){const t=document.createElement('table');t.innerHTML=`<thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(v=>`<td>${esc(display(v))}</td>`).join('')}</tr>`).join('')}</tbody>`;return t}
function datasetFallback(area,sub){const out=[];if(area==='activity'){const rows=readStore('hd20GMES5SAutoImproveRawV1');out.push({title:sub==='manage'?'5S 활동 원천목록':'5S 활동 실적 원천목록',table:makeTable(['Activity ID','일자','유형','생산팀','작업장','등록자','문제점','개선내용','상태','BEFORE','AFTER','고도화 후보'],rows.map(x=>[x.id,x.date||x.regDate,x.type||x.category,x.team,x.workplace||x.location||x.title,x.author||x.owner,x.problem||x.issue,x.improvement||x.action||x.improve,x.status||x.judgeState,(x.before||x.evidence)?'등록':'미등록',(x.after||x.afterEvidence)?'등록':'미등록',advancementCandidate(x)?'후보':'—']))})}else if(area==='advancement'){const all=readStore('hd20GMES5SAutoImproveRawV1'),rows=sub==='standard'?all.filter(advancementConfirmed):all.filter(advancementCandidate);out.push({title:sub==='judge'?'고도화 후보·판정 원천목록':'고도화 확정·전개 원천목록',table:makeTable(['Activity ID','후보일','생산팀','작업장','판정상태','공식확정','확정일','유지상태','수평전개'],rows.map(x=>[x.id,x.date||x.regDate,x.team,x.workplace||x.location||x.title,x.judgeState||x.status,advancementConfirmed(x)?'확정':'미확정',x.confirmedAt||x.judgedAt,x.maintainState||x.auditState,(x.horizontalRollout||/전개/.test(txt(x.rolloutState)))?'전개':'—']))})}else if(area==='audit'){const rows=readStore('hd20AuditRandomDrawsV1'),actions=readStore('hd20ActionCasesV2');out.push({title:sub==='retention'?'6개월 유지관리 원천목록':'Audit 대상·실시 원천목록',table:makeTable(['Audit ID','선정일','생산팀','작업장','Audit일','결과','상태','종료평가','Action 연계','유지 Risk'],rows.map(x=>{const id=auditId(x),linked=actions.filter(a=>id&&actionSourceId(a)===id),finalState=txt(x.finalEvaluation||x.auditFinalState),risk=/미흡|부적합|실패|해제|중지/.test(finalState)||linked.some(closedLoopRecurrence);return[id,x.date||x.drawDate,x.team,x.workplace,x.auditDate,x.auditResult||x.result,x.status,x.finalEvaluation,linked.length,risk?'재발/미흡':'—']}))})}else if(area==='action'){const rows=readStore('hd20ActionCasesV2');out.push({title:sub==='manage'?'개선조치 원천목록':'효과·재발 검증 원천목록',table:makeTable(['Action ID','원천 Audit ID','등록일','생산팀','담당','문제','조치','기한','조치상태','운영상태','효과검증','재발'],rows.map(x=>[x.id,actionSourceId(x),x.registeredAt||x.date,x.team,x.owner||x.assignee,x.problem,x.action||x.improvement,dueOf(x),x.status,actionState(x),x.effectState||x.effectResult||(x.effectVerified?'검증완료':'미검증'),recurrenceKnown(x)?(recurrenceConfirmed(x)?'재발':'미발생'):'미확인']))})}return out.filter(s=>s.table.tBodies[0].rows.length)}
function openGrid(area=state.area,sub=state.sub){const m=ensureGridModal(),body=$('#hd20GridBody',m),p=contract(area,sub);let sets=collectVisible(area);if(!sets.length)sets=datasetFallback(area,sub);$('#hd20GridTitle',m).textContent=`${p.title} · 상세 데이터`;$('#hd20GridMeta',m).textContent=sets.length?`현재 업무화면/원천데이터 기준 ${sets.length}개 데이터셋`:'현재 표시 가능한 실제 데이터가 없습니다.';body.innerHTML='';if(!sets.length){body.innerHTML='<div class="hd20GridEmpty"><b>표시할 상세 데이터가 없습니다.</b><p>현재 원천데이터가 없거나 해당 업무단계에서 생성된 데이터가 없습니다. 임의 데이터를 생성하지 않습니다.</p></div>'}else sets.forEach(s=>{const sec=document.createElement('section');sec.className='hd20GridSection';const h=document.createElement('h3');h.textContent=s.title;sec.append(h,s.table);body.appendChild(sec)});$('#hd20GridSearch',m).value='';m.classList.add('on');setTimeout(()=>$('#hd20GridSearch',m)?.focus(),30)}
function filterGrid(e){const q=e.target.value.trim().toLowerCase();$$('#hd20GridBody tbody tr').forEach(tr=>tr.hidden=!!q&&!tr.textContent.toLowerCase().includes(q))}
function downloadGridCsv(){const tables=$$('#hd20GridBody table');if(!tables.length)return;const rows=[];tables.forEach((t,ti)=>{if(ti)rows.push([]);rows.push([t.closest('.hd20GridSection')?.querySelector('h3')?.textContent||'상세 데이터']);$$('tr',t).filter(tr=>!tr.hidden).forEach(tr=>rows.push($$('th,td',tr).map(x=>x.textContent.trim())))});const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`HD20_${state.area}_${state.sub}_${seoulDate()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function render(area){const bar=ensure(),items=MAP[area]||[];state.area=area;if(!items.some(x=>x[0]===state.sub))state.sub=items[0]?.[0]||'';bar.innerHTML=items.map(([k,n])=>`<button type="button" data-sub="${k}" class="${k===state.sub?'on':''}">${n}</button>`).join('');$$('button',bar).forEach(b=>b.onclick=()=>select(area,b.dataset.sub));renderPurpose(area,state.sub);requestAnimationFrame(()=>apply(area,state.sub))}
function show(el,on){if(el)el.classList.toggle('hd20SubHidden',!on)}function showAll(root,sel='.awCard'){if(root)$$(sel,root).forEach(el=>show(el,true))}
function applyDashboard(sub){const cards=$('.cards'),main=$('.mainGrid'),bottom=$('.bottomGrid'),priority=$('#hd20DashboardPriority'),bridge=$('#hd20OperationalBridge');if(sub==='summary'){show(cards,true);show(main,true);show(priority,true);show(bridge,false);show(bottom,false);if(main){show(main.children?.[0],true);show($('.sideStack',main),true)}}else{show(cards,false);show(main,true);show(priority,true);show(bridge,true);show(bottom,true);if(main){show(main.children?.[0],false);show($('.sideStack',main),true)}}}
function applyActivity(sub){const root=$('#awActivity');if(!root)return;root.dataset.subview=sub;showAll(root);show($('.awFlow',root),true);show($('.awGrid',root),true);const form=$('.awRegisterFormCard',root);if(form)show(form,sub==='manage')}
function applyAdvancement(sub){const conversion=$('#performanceConversionAnalysis'),work=$('#awWorkplace');document.querySelector('.app')?.classList.add('awFocused');if(conversion){conversion.classList.add('on');show(conversion,true);conversion.classList.toggle('hd20AdvancementStandard',sub==='standard');conversion.dataset.subview=sub}if(work){work.classList.add('on');show(work,true);work.dataset.subview=sub;showAll(work);show($('.awFlow',work),true);show($('.awGrid',work),true)}}
function applyAudit(sub){const root=$('#awAudit');if(!root)return;root.dataset.subview=sub;showAll(root);show($('.awFlow',root),true);show($('.awAuditLane',root),true);const draw=$('.auditDraw',root),batch=$('#hd20AuditBatchExecution',root),closed=$('.auditClosedLoop',root),ongoing=$('.audit6m',root),closeEval=document.getElementById('hd20AuditCloseEvaluation');show(draw,sub==='draw');show(batch,sub==='draw');show(closed,sub==='inspect');show(ongoing,sub==='ongoing');show(closeEval,sub==='retention')}
function ensureActionVerify(root){let host=$('#hd20ActionVerifyStatus',root);if(!host){host=document.createElement('section');host.id='hd20ActionVerifyStatus';host.className='awCard';const anchor=$('.awKpis',root)||$('.awFlow',root)||$('.awHero',root);anchor?.insertAdjacentElement('afterend',host)}return host}
function renderActionVerify(root){const host=ensureActionVerify(root);if(!host)return;const rows=readStore('hd20ActionCasesV2'),done=rows.filter(doneStatus),verified=done.filter(effectVerified),pendingVerify=done.filter(x=>!effectVerified(x)),recurrence=verified.filter(recurrenceConfirmed);host.innerHTML=`<div class="awHead"><div><b>효과·재발 검증현황</b><small>실제 개선조치 데이터 기준 · 미입력 결과는 임의 생성하지 않습니다.</small></div></div><div class="awKpis"><div><small>전체 개선요청</small><b>${rows.length}건</b></div><div><small>조치 진행·대기</small><b>${rows.length-done.length}건</b></div><div><small>완료·효과검증 대상</small><b>${done.length}건</b></div><div><small>효과검증 완료</small><b>${verified.length}건</b></div><div><small>재발 확인</small><b>${recurrence.length}건</b></div></div><div class="awHint" style="margin-top:10px">${pendingVerify.length?`완료 ${done.length}건 중 효과검증 미입력 ${pendingVerify.length}건은 <b>검증 대기</b> 상태입니다.`:done.length?'완료된 개선조치는 모두 효과검증 결과가 입력되어 있습니다.':'완료된 개선조치가 없어 효과검증 대상이 없습니다.'}</div>`}
function applyAction(sub){const root=$('#awAction');if(!root)return;root.dataset.subview=sub;showAll(root);show($('.awFlow',root),true);show($('.awKpis',root),true);const form=$('.amRegisterFormCard',root),verify=ensureActionVerify(root);show(form,sub==='manage');if(sub==='verify'){renderActionVerify(root);show(verify,true)}else{show(verify,false)}}
function apply(area,sub){if(area==='dashboard')applyDashboard(sub);else if(area==='activity')applyActivity(sub);else if(area==='advancement')applyAdvancement(sub);else if(area==='audit')applyAudit(sub);else if(area==='action')applyAction(sub);window.dispatchEvent(new CustomEvent('hd20-subtab-changed',{detail:{area,sub}}))}
function select(area,sub){state={area,sub};$$('button',ensure()).forEach(b=>b.classList.toggle('on',b.dataset.sub===sub));apply(area,sub);renderPurpose(area,sub)}
function syncArea(area){if(!MAP[area])return;state.sub=(MAP[area]||[])[0]?.[0]||'';state.area=area;const bar=ensure(),items=MAP[area]||[];bar.innerHTML=items.map(([k,n])=>`<button type="button" data-sub="${k}" class="${k===state.sub?'on':''}">${n}</button>`).join('');$$('button',bar).forEach(b=>b.onclick=()=>select(area,b.dataset.sub));renderPurpose(area,state.sub);requestAnimationFrame(()=>apply(area,state.sub))}
function bindMain(){const nav=$('.beginnerNav');if(!nav)return;nav.addEventListener('click',e=>{const b=e.target.closest('button[data-key]');if(!b)return;setTimeout(()=>syncArea(b.dataset.key),60)});window.addEventListener('hd20-nav-area-changed',e=>{const area=e.detail?.area;if(!MAP[area])return;if(state.area===area&&$('#hd20PurposePanel'))return;setTimeout(()=>syncArea(area),0)})}
function boot(){ensure();ensureGridModal();bindMain();window.addEventListener('hd20-action-updated',()=>{if(state.area==='action'&&state.sub==='verify')renderActionVerify($('#awAction'))});setTimeout(()=>render(window.HD20_NAV?.active?.()||'dashboard'),120)}
window.HD20_SUBNAV={render,select,state:()=>({...state}),map:MAP,contracts:CONTRACT,purpose:CONTRACT,contractMap:(area)=>area?{[area]:MAP[area]}:MAP,contractPurpose:(area)=>area?Object.fromEntries(Object.entries(CONTRACT).filter(([k])=>k.startsWith(area+'.'))):CONTRACT,openGrid:()=>openGrid(state.area,state.sub),advancementType,advancementCandidate,advancementConfirmed};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();