(()=>{'use strict';
const KEYS=['hd20GMES5SAutoImproveRawV1','hd20ActionCasesV2','hd20AuditRandomDrawsV1','hd20OperatingPolicyV1','hd20AuditChecklistV1','hd20TeamLeaderMasterV1'];
const ROW='canonical_v1',META='hd20DbSyncMetaV1';let client=null,user=null,ready=false,applying=false,timer=null,patched=false,booting=false,lastRemoteAt='';
const parse=v=>{try{return JSON.parse(v)}catch{return v}};
function snapshot(){const payload={};KEYS.forEach(k=>{const v=localStorage.getItem(k);if(v!==null)payload[k]=parse(v)});return payload}
function meta(){try{return JSON.parse(localStorage.getItem(META)||'{}')}catch{return{}}}
function setMeta(patch){const m={...meta(),...patch};localStorage.setItem(META,JSON.stringify(m));return m}
function emit(state,detail={}){window.dispatchEvent(new CustomEvent('hd20-db-status',{detail:{state,at:new Date().toISOString(),...detail}}))}
function notify(source='supabase'){['hd20-db-synced','hd20-kpi-source-updated','hd20-gmes-5s-imported','hd20-gmes-5s-judged'].forEach(name=>window.dispatchEvent(new CustomEvent(name,{detail:{source}})))}
function apply(payload){if(!payload||typeof payload!=='object')return;applying=true;try{KEYS.forEach(k=>{if(Object.prototype.hasOwnProperty.call(payload,k))localStorage.setItem(k,typeof payload[k]==='string'?payload[k]:JSON.stringify(payload[k]))})}finally{applying=false}notify()}
async function fetchRemote(){if(!client||!user)return null;const {data,error}=await client.from('hd20_app_state').select('payload,updated_at,updated_by').eq('id',ROW).maybeSingle();if(error){emit('error',{message:error.message});console.error('[HD20 DB] fetch',error);return null}return data||null}
async function pull(){emit('syncing',{mode:'pull'});const data=await fetchRemote();if(data?.payload&&Object.keys(data.payload).length){apply(data.payload);lastRemoteAt=data.updated_at||'';setMeta({lastPullAt:new Date().toISOString(),remoteUpdatedAt:lastRemoteAt});emit('ready',{mode:'pull',remoteUpdatedAt:lastRemoteAt});return data}emit('ready',{mode:'pull',empty:true});return data}
async function push(){if(!client||!user||applying)return false;emit('syncing',{mode:'push'});const remote=await fetchRemote(),m=meta();if(remote?.updated_at&&m.remoteUpdatedAt&&remote.updated_at!==m.remoteUpdatedAt){apply(remote.payload||{});lastRemoteAt=remote.updated_at;setMeta({lastPullAt:new Date().toISOString(),remoteUpdatedAt:remote.updated_at,conflictResolvedAt:new Date().toISOString()});emit('ready',{mode:'conflict-pull',remoteUpdatedAt:remote.updated_at});return false}const payload=snapshot(),stamp=new Date().toISOString();const {data,error}=await client.from('hd20_app_state').upsert({id:ROW,payload,updated_by:user.id,updated_at:stamp},{onConflict:'id'}).select('updated_at').single();if(error){emit('error',{message:error.message});console.error('[HD20 DB] push',error);return false}lastRemoteAt=data?.updated_at||stamp;setMeta({lastPushAt:new Date().toISOString(),remoteUpdatedAt:lastRemoteAt});emit('ready',{mode:'push',remoteUpdatedAt:lastRemoteAt});return true}
function queue(){if(!ready||applying)return;clearTimeout(timer);timer=setTimeout(push,500)}
function patchStorage(){if(patched)return;patched=true;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){original.call(this,k,v);if(this===localStorage&&KEYS.includes(k))queue()}}
function installBadge(){const controls=document.querySelector('.controls');if(!controls||document.getElementById('hd20DbStatus'))return;const badge=document.createElement('span');badge.id='hd20DbStatus';badge.className='hd20DbStatus';badge.textContent='DB 연결 확인중';controls.appendChild(badge);window.addEventListener('hd20-db-status',e=>{const s=e.detail?.state;if(s==='syncing'){badge.textContent='DB 동기화중';badge.dataset.state='syncing'}else if(s==='error'){badge.textContent='DB 오류';badge.dataset.state='error'}else{badge.textContent='DB 연결됨';badge.dataset.state='ready'}})}
async function boot(){if(window.HD20_AUTH_BYPASS)return;if(booting)return;booting=true;try{client=window.HD20_SUPABASE;if(!client){booting=false;setTimeout(boot,120);return}const {data}=await client.auth.getSession();user=data?.session?.user||null;if(!user)return;installBadge();patchStorage();const localBefore=snapshot(),hasLocal=Object.keys(localBefore).length>0;const remote=await fetchRemote(),hasRemote=!!(remote?.payload&&Object.keys(remote.payload).length);ready=true;if(hasRemote){apply(remote.payload);lastRemoteAt=remote.updated_at||'';setMeta({lastPullAt:new Date().toISOString(),remoteUpdatedAt:lastRemoteAt});emit('ready',{mode:'initial-pull',remoteUpdatedAt:lastRemoteAt});const hydrateKey='hd20-db-hydrated:'+user.id;if(!sessionStorage.getItem(hydrateKey)){sessionStorage.setItem(hydrateKey,lastRemoteAt||'1');setTimeout(()=>location.reload(),80)}}else if(hasLocal){await push()}else emit('ready',{mode:'empty'});window.HD20_DB_SYNC={pull,push,fetchRemote,keys:[...KEYS],ready:()=>ready,status:()=>({ready,lastRemoteAt,meta:meta()})}}finally{booting=false}}
window.addEventListener('hd20-auth-ready',e=>{user=e.detail?.user||user;boot()});window.addEventListener('hd20-auth-bypass',()=>{window.HD20_DB_SYNC={pull:async()=>null,push:async()=>false,keys:[...KEYS],ready:()=>false,status:()=>({ready:false,bypass:true})}});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,100),{once:true}):setTimeout(boot,100);
})();