(()=>{'use strict';
const KEYS=['hd20GMES5SAutoImproveRawV1','hd20ActionCasesV2','hd20AuditRandomDrawsV1','hd20OperatingPolicyV1','hd20AuditChecklistV1','hd20TeamLeaderMasterV1'];
const ROW='canonical_v1';let client=null,user=null,ready=false,applying=false,timer=null,patched=false,booting=false;
const parse=v=>{try{return JSON.parse(v)}catch{return v}};
function snapshot(){const payload={};KEYS.forEach(k=>{const v=localStorage.getItem(k);if(v!==null)payload[k]=parse(v)});return payload}
function notify(source='supabase'){['hd20-db-synced','hd20-kpi-source-updated','hd20-gmes-5s-imported','hd20-gmes-5s-judged'].forEach(name=>window.dispatchEvent(new CustomEvent(name,{detail:{source}})))}
function apply(payload){if(!payload||typeof payload!=='object')return;applying=true;try{KEYS.forEach(k=>{if(Object.prototype.hasOwnProperty.call(payload,k))localStorage.setItem(k,typeof payload[k]==='string'?payload[k]:JSON.stringify(payload[k]))})}finally{applying=false}notify()}
async function pull(){if(!client||!user)return null;const {data,error}=await client.from('hd20_app_state').select('payload,updated_at').eq('id',ROW).maybeSingle();if(error){console.error('[HD20 DB] pull',error);return null}if(data?.payload&&Object.keys(data.payload).length){apply(data.payload);return data}return data||null}
async function push(){if(!client||!user||applying)return false;const payload=snapshot();const {error}=await client.from('hd20_app_state').upsert({id:ROW,payload,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'id'});if(error){console.error('[HD20 DB] push',error);return false}return true}
function queue(){if(!ready||applying)return;clearTimeout(timer);timer=setTimeout(push,500)}
function patchStorage(){if(patched)return;patched=true;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){original.call(this,k,v);if(this===localStorage&&KEYS.includes(k))queue()}}
async function boot(){if(window.HD20_AUTH_BYPASS)return;if(booting)return;booting=true;try{client=window.HD20_SUPABASE;if(!client){booting=false;setTimeout(boot,120);return}const {data}=await client.auth.getSession();user=data?.session?.user||null;if(!user)return;patchStorage();const localBefore=snapshot(),hasLocal=Object.keys(localBefore).length>0;const remote=await pull(),hasRemote=!!(remote?.payload&&Object.keys(remote.payload).length);ready=true;if(!hasRemote&&hasLocal)await push();window.HD20_DB_SYNC={pull,push,keys:[...KEYS],ready:()=>ready};const hydrateKey='hd20-db-hydrated:'+user.id;if(hasRemote&&!sessionStorage.getItem(hydrateKey)){sessionStorage.setItem(hydrateKey,remote.updated_at||'1');setTimeout(()=>location.reload(),80)}}finally{booting=false}}
window.addEventListener('hd20-auth-ready',e=>{user=e.detail?.user||user;boot()});window.addEventListener('hd20-auth-bypass',()=>{window.HD20_DB_SYNC={pull:async()=>null,push:async()=>false,keys:[...KEYS],ready:()=>false}});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,100),{once:true}):setTimeout(boot,100);
})();