(()=>{'use strict';
const MAIL_SESSION_KEY='hd20_company_session_v1';
const REGISTERED_EMAIL_KEY='hd20_registered_company_email_v1';
const SESSION_MS=5*60*60*1000;
const EXTEND_THROTTLE_MS=5*60*1000;
let lastExtendAt=0,sessionExpiryHandling=false;const $=(s,r=document)=>r.querySelector(s);
function normalizeMail(email){return String(email||'').trim().toLowerCase()}
function validHdMail(email){return /^[^@\s]+@hd\.com$/i.test(String(email||'').trim())}
function readMailSession(){try{const s=JSON.parse(localStorage.getItem(MAIL_SESSION_KEY)||'null');if(!s||!validHdMail(s.email)||!s.expiresAt||Date.now()>=s.expiresAt){localStorage.removeItem(MAIL_SESSION_KEY);return null}return s}catch{return null}}
function saveMailSession(email){const s={email:normalizeMail(email),expiresAt:Date.now()+SESSION_MS};localStorage.setItem(MAIL_SESSION_KEY,JSON.stringify(s));localStorage.setItem(REGISTERED_EMAIL_KEY,s.email);return s}
function extendMailSession(){const s=readMailSession();if(!s)return;const now=Date.now();if(now-lastExtendAt<EXTEND_THROTTLE_MS)return;lastExtendAt=now;s.expiresAt=now+SESSION_MS;localStorage.setItem(MAIL_SESSION_KEY,JSON.stringify(s));renderSessionChip(s)}
function gate(){let el=$('#hd20AuthGate');if(el)return el;el=document.createElement('div');el.id='hd20AuthGate';el.className='hd20AuthGate';document.body.appendChild(el);return el}
function invalidPopup(){let el=$('#hd20InvalidPopup');if(el)return el;el=document.createElement('div');el.id='hd20InvalidPopup';el.innerHTML=`<section class="hd20InvalidCard"><h2>접근 제한</h2><p>본 자료를 열람할 수 없습니다.<br><b>@hd.com 회사 이메일만 사용할 수 있습니다.</b></p><button class="hd20InvalidBtn" id="hd20InvalidClose" type="button">확인</button></section>`;document.body.appendChild(el);$('#hd20InvalidClose',el)?.addEventListener('click',()=>{el.classList.remove('on');setTimeout(()=>$('#hd20MailGateEmail')?.focus(),0)});el.addEventListener('click',e=>{if(e.target===el)el.classList.remove('on')});return el}
function showInvalidPopup(){invalidPopup().classList.add('on')}
function renderMailGate(){const el=gate(),remembered=localStorage.getItem(REGISTERED_EMAIL_KEY)||'';el.innerHTML=`<div class="hd20AuthBox"><span class="hd20AuthMark">HDPS · 사내 전용</span><h1>사내메일 인증</h1><p>HD-20은 사내 구성원 전용 시스템입니다. 회사 이메일을 입력해 주세요.</p><form class="hd20AuthForm" id="hd20MailGateForm"><label>사내 이메일<input id="hd20MailGateEmail" type="email" autocomplete="email" required placeholder="name@hd.com" value="${remembered.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"></label><button class="hd20AuthSubmit" type="submit">인증 후 접속</button></form><div class="hd20AuthError" id="hd20MailGateError"></div><div class="hd20AuthFoot">허용 이메일 형태: @hd.com · 인증 유지시간: 5시간</div></div>`;el.classList.add('on');document.body.style.overflow='hidden';$('#hd20MailGateForm')?.addEventListener('submit',e=>{e.preventDefault();const email=$('#hd20MailGateEmail')?.value?.trim()||'',err=$('#hd20MailGateError');if(!validHdMail(email)){if(err)err.textContent='';showInvalidPopup();return}const s=saveMailSession(email);el.classList.remove('on');enterApp(s)});setTimeout(()=>$('#hd20MailGateEmail')?.focus(),0)}
function loading(){let el=$('#hd20AuthLoading');if(el)return el;el=document.createElement('div');el.id='hd20AuthLoading';el.className='hd20AuthLoading';el.textContent='인증 상태를 확인하고 있습니다…';document.body.appendChild(el);return el}
function setAppVisible(on){document.documentElement.classList.remove('hd20-auth-pending');loading().classList.toggle('hide',on);gate().classList.toggle('on',!on);document.body.style.overflow=on?'':'hidden'}
function renderSessionChip(s){if(!s)return;let chip=$('#hd20MailSessionChip');if(!chip){chip=document.createElement('span');chip.id='hd20MailSessionChip';chip.className='hd20AuthUser';const controls=$('.controls');controls?.appendChild(chip)}const remain=Math.max(0,s.expiresAt-Date.now()),h=Math.floor(remain/3600000),m=Math.floor((remain%3600000)/60000);chip.innerHTML=`<span>●</span><b>${s.email}</b><small>${h}시간 ${m}분</small>`}
function ensureLogoutButton(){const controls=$('.controls');if(!controls)return;let out=$('#hd20Logout');if(!out){out=document.createElement('button');out.id='hd20Logout';out.className='hd20Logout';out.type='button';out.textContent='로그아웃';controls.appendChild(out);out.onclick=()=>{localStorage.removeItem(MAIL_SESSION_KEY);location.reload()}}}
function clearUser(){$('#hd20MailSessionChip')?.remove();$('#hd20Logout')?.remove()}
/* 사내메일 인증만으로 앱 진입: Supabase 비밀번호 로그인 단계 없음(DB 동기화도 사용하지 않음) */
function enterApp(session){window.HD20_AUTH_BYPASS=true;setAppVisible(true);renderSessionChip(session);ensureLogoutButton();window.dispatchEvent(new CustomEvent('hd20-auth-bypass'))}
function showBootError(error){console.error('[HD20 AUTH] bootstrap failed',error);document.documentElement.classList.remove('hd20-auth-pending');loading().classList.add('hide');const el=gate();el.innerHTML=`<div class="hd20AuthBox"><span class="hd20AuthMark">HDPS · ACCESS CHECK</span><h1>접속 초기화 오류</h1><p>인증 초기화 중 문제가 발생했습니다. 빈 화면으로 잠그지 않고 오류 상태를 표시합니다.</p><button class="hd20AuthSubmit" id="hd20AuthRetry" type="button">다시 시도</button><div class="hd20AuthError">네트워크 또는 인증 모듈 연결 상태를 확인해 주세요.</div></div>`;el.classList.add('on');document.body.style.overflow='hidden';$('#hd20AuthRetry',el)?.addEventListener('click',()=>location.reload())}
async function handleExpiredCompanySession(){if(sessionExpiryHandling)return;sessionExpiryHandling=true;try{localStorage.removeItem(MAIL_SESSION_KEY);clearUser();loading().classList.add('hide');document.documentElement.classList.remove('hd20-auth-pending');renderMailGate()}finally{sessionExpiryHandling=false}}
function bindSlidingSession(){['click','keydown','touchstart'].forEach(ev=>document.addEventListener(ev,extendMailSession,{passive:true}));document.addEventListener('visibilitychange',()=>{if(!document.hidden){const s=readMailSession();if(s)extendMailSession();else handleExpiredCompanySession()}});setInterval(()=>{const s=readMailSession();if(!s){handleExpiredCompanySession();return}renderSessionChip(s)},60000)}
async function boot(){try{if(['127.0.0.1','localhost'].includes(location.hostname)){window.HD20_AUTH_BYPASS=true;document.documentElement.classList.remove('hd20-auth-pending');document.body.style.overflow='';window.dispatchEvent(new CustomEvent('hd20-auth-bypass'));return}loading();invalidPopup();bindSlidingSession();const s=readMailSession();if(!s){document.documentElement.classList.remove('hd20-auth-pending');loading().classList.add('hide');renderMailGate();return}loading().classList.add('hide');enterApp(s)}catch(e){showBootError(e)}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();
