(()=>{'use strict';
const SUPABASE_URL='https://sbqpyrynamviaojwfrrp.supabase.co';
const SUPABASE_KEY='sb_publishable_eMerbDTZ96HkolTfUCxlLQ_cEocSRBy';
const MAIL_SESSION_KEY='hd20_company_session_v1';
const REGISTERED_EMAIL_KEY='hd20_registered_company_email_v1';
const SESSION_MS=5*60*60*1000;
const EXTEND_THROTTLE_MS=5*60*1000;
let client=null,lastExtendAt=0;const $=(s,r=document)=>r.querySelector(s);
function validHdMail(email){return /^[^@\s]+@hd\.com$/i.test(String(email||'').trim())}
function readMailSession(){try{const s=JSON.parse(localStorage.getItem(MAIL_SESSION_KEY)||'null');if(!s||!validHdMail(s.email)||!s.expiresAt||Date.now()>=s.expiresAt){localStorage.removeItem(MAIL_SESSION_KEY);return null}return s}catch{return null}}
function saveMailSession(email){const s={email:String(email).trim().toLowerCase(),expiresAt:Date.now()+SESSION_MS};localStorage.setItem(MAIL_SESSION_KEY,JSON.stringify(s));localStorage.setItem(REGISTERED_EMAIL_KEY,s.email);return s}
function extendMailSession(){const s=readMailSession();if(!s)return;const now=Date.now();if(now-lastExtendAt<EXTEND_THROTTLE_MS)return;lastExtendAt=now;s.expiresAt=now+SESSION_MS;localStorage.setItem(MAIL_SESSION_KEY,JSON.stringify(s));renderSessionChip(s)}
function gate(){let el=$('#hd20AuthGate');if(el)return el;el=document.createElement('div');el.id='hd20AuthGate';el.className='hd20AuthGate';document.body.appendChild(el);return el}
function invalidPopup(){let el=$('#hd20InvalidPopup');if(el)return el;el=document.createElement('div');el.id='hd20InvalidPopup';el.innerHTML=`<section class="hd20InvalidCard"><h2>접근 제한</h2><p>본 자료를 열람할 수 없습니다.<br><b>@hd.com 회사 이메일만 사용할 수 있습니다.</b></p><button class="hd20InvalidBtn" id="hd20InvalidClose" type="button">확인</button></section>`;document.body.appendChild(el);$('#hd20InvalidClose',el)?.addEventListener('click',()=>{el.classList.remove('on');setTimeout(()=>$('#hd20MailGateEmail')?.focus()||$('#hd20AuthEmail')?.focus(),0)});el.addEventListener('click',e=>{if(e.target===el)el.classList.remove('on')});return el}
function showInvalidPopup(){invalidPopup().classList.add('on')}
function renderMailGate(){const el=gate(),remembered=localStorage.getItem(REGISTERED_EMAIL_KEY)||'';el.innerHTML=`<div class="hd20AuthBox"><span class="hd20AuthMark">HDPS · 사내 전용</span><h1>사내메일 인증</h1><p>HD-20은 사내 구성원 전용 시스템입니다. 회사 이메일을 입력해 주세요.</p><form class="hd20AuthForm" id="hd20MailGateForm"><label>사내 이메일<input id="hd20MailGateEmail" type="email" autocomplete="email" required placeholder="name@hd.com" value="${remembered.replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"></label><button class="hd20AuthSubmit" type="submit">인증 후 접속</button></form><div class="hd20AuthError" id="hd20MailGateError"></div><div class="hd20AuthFoot">허용 이메일 형태: @hd.com · 인증 유지시간: 5시간</div></div>`;el.classList.add('on');document.body.style.overflow='hidden';$('#hd20MailGateForm')?.addEventListener('submit',e=>{e.preventDefault();const email=$('#hd20MailGateEmail')?.value?.trim()||'',err=$('#hd20MailGateError');if(!validHdMail(email)){if(err)err.textContent='';showInvalidPopup();return}saveMailSession(email);el.classList.remove('on');startSupabase()});setTimeout(()=>$('#hd20MailGateEmail')?.focus(),0)}
function renderSupabaseGate(){const el=gate();el.innerHTML=`<div class="hd20AuthBox"><span class="hd20AuthMark">HDPS · SECURE ACCESS</span><h1>울산캠퍼스 5S 활동관리</h1><p>사내메일 인증이 완료되었습니다. 데이터 동기화를 위해 등록된 계정으로 로그인해 주세요.</p><form class="hd20AuthForm" id="hd20AuthForm"><label>이메일<input id="hd20AuthEmail" type="email" autocomplete="username" required placeholder="name@hd.com"></label><label>비밀번호<input id="hd20AuthPassword" type="password" autocomplete="current-password" required placeholder="비밀번호"></label><button class="hd20AuthSubmit" id="hd20AuthSubmit" type="submit">로그인</button></form><div class="hd20AuthError" id="hd20AuthError"></div><div class="hd20AuthFoot">허용 이메일 형태: @hd.com · Supabase Authentication에 등록된 사용자만 데이터 동기화 기능을 사용할 수 있습니다.</div></div>`;el.classList.add('on');bindForm()}
function loading(){let el=$('#hd20AuthLoading');if(el)return el;el=document.createElement('div');el.id='hd20AuthLoading';el.className='hd20AuthLoading';el.textContent='인증 상태를 확인하고 있습니다…';document.body.appendChild(el);return el}
function setAppVisible(on){document.documentElement.classList.remove('hd20-auth-pending');loading().classList.toggle('hide',on);gate().classList.toggle('on',!on);document.body.style.overflow=on?'':'hidden'}
function authenticated(session){if(!session?.user)return;showUser(session);setAppVisible(true);const ms=readMailSession();if(ms)renderSessionChip(ms);window.dispatchEvent(new CustomEvent('hd20-auth-ready',{detail:{user:session.user}}))}
function renderSessionChip(s){if(!s)return;let chip=$('#hd20MailSessionChip');if(!chip){chip=document.createElement('span');chip.id='hd20MailSessionChip';chip.className='hd20AuthUser';const controls=$('.controls');controls?.appendChild(chip)}const remain=Math.max(0,s.expiresAt-Date.now()),h=Math.floor(remain/3600000),m=Math.floor((remain%3600000)/60000);chip.innerHTML=`<span>●</span><b>${s.email}</b><small>${h}시간 ${m}분</small>`}
function showUser(session){const controls=$('.controls');if(!controls||!session?.user)return;let badge=$('#hd20AuthUser');if(!badge){badge=document.createElement('span');badge.id='hd20AuthUser';badge.className='hd20AuthUser';controls.appendChild(badge)}badge.innerHTML=`<span>●</span><b>${session.user.email||'사용자'}</b>`;let out=$('#hd20Logout');if(!out){out=document.createElement('button');out.id='hd20Logout';out.className='hd20Logout';out.type='button';out.textContent='로그아웃';controls.appendChild(out);out.onclick=async()=>{out.disabled=true;localStorage.removeItem(MAIL_SESSION_KEY);await client.auth.signOut();location.reload()}}}
function clearUser(){$('#hd20AuthUser')?.remove();$('#hd20MailSessionChip')?.remove();$('#hd20Logout')?.remove()}
function bindForm(){const form=$('#hd20AuthForm');if(!form||form.dataset.bound)return;form.dataset.bound='1';form.addEventListener('submit',async e=>{e.preventDefault();const email=$('#hd20AuthEmail').value.trim(),password=$('#hd20AuthPassword').value,btn=$('#hd20AuthSubmit'),err=$('#hd20AuthError');err.textContent='';if(!validHdMail(email)){showInvalidPopup();return}btn.disabled=true;btn.textContent='로그인 중…';const {error}=await client.auth.signInWithPassword({email,password});btn.disabled=false;btn.textContent='로그인';if(error)err.textContent='로그인에 실패했습니다. 이메일과 비밀번호를 확인해 주세요.'})}
function bindSlidingSession(){['click','keydown','touchstart'].forEach(ev=>document.addEventListener(ev,extendMailSession,{passive:true}));document.addEventListener('visibilitychange',()=>{if(!document.hidden)extendMailSession()});setInterval(()=>{const s=readMailSession();if(!s){const g=gate();if(!g.classList.contains('on')){clearUser();renderMailGate()}return}renderSessionChip(s)},60000)}
async function startSupabase(){loading();if(!window.supabase?.createClient){gate().classList.add('on');gate().innerHTML=`<div class="hd20AuthBox"><h1>인증 모듈 오류</h1><p>인증 모듈을 불러오지 못했습니다. 네트워크 상태를 확인해 주세요.</p></div>`;document.documentElement.classList.remove('hd20-auth-pending');return}if(!client){client=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});window.HD20_SUPABASE=client;client.auth.onAuthStateChange((event,session)=>{if(session)authenticated(session);else{clearUser();renderSupabaseGate();loading().classList.add('hide')}})}const {data}=await client.auth.getSession();if(data?.session)authenticated(data.session);else{document.documentElement.classList.remove('hd20-auth-pending');loading().classList.add('hide');renderSupabaseGate()}}
async function boot(){if(['127.0.0.1','localhost'].includes(location.hostname)){window.HD20_AUTH_BYPASS=true;document.documentElement.classList.remove('hd20-auth-pending');document.body.style.overflow='';window.dispatchEvent(new CustomEvent('hd20-auth-bypass'));return}loading();invalidPopup();bindSlidingSession();const s=readMailSession();if(!s){document.documentElement.classList.remove('hd20-auth-pending');loading().classList.add('hide');renderMailGate();return}renderSessionChip(s);await startSupabase()}
document.documentElement.classList.add('hd20-auth-pending');document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
})();