(()=>{'use strict';
const KEYS=['hd20GMES5SAutoImproveRawV1','hd20ActionCasesV2','hd20AuditRandomDrawsV1','hd20OperatingPolicyV1','hd20AuditChecklistV1','hd20TeamLeaderMasterV1','hd20TeamHeadcountMasterV1'];
const ROW='canonical_v1',META='hd20DbSyncMetaV1';let client=null,user=null,ready=false,applying=false,timer=null,patched=false,booting=false,lastRemoteAt='';
const parse=v=>{try{return JSON.parse(v)}catch{return v}};
function isNonProdRow(x){if(!x||typeof x!=='object')return false;const source=String(x.source||'').toLowerCase(),id=String(x.id||'').toUpperCase(),sourceCaseId=String(x.sourceCaseId||'').toUpperCase(),email=String(x.email||'').toLowerCase();return x.isDemo===true||x.isTest===true||source==='demo-seed'||source==='e2e-fixture'||id.startsWith('DEMO-')||id.startsWith('E2E-')||id.includes('AUTO-DEMO-')||sourceCaseId.startsWith('DEMO-')||sourceCaseId.startsWith('E2E-')||email.endsWith('@hd-hyundai-demo.co.kr')}
function sanitizeStore(v){return Array.isArray(v)?v.filter(x=>!isNonProdRow(x)):v}
function unsafeRows(v){return Array.isArray(v)?v.filter(isNonProdRow):[]}
function snapshot(){const payload={};KEYS.forEach(k=>{const v=localStorage.getItem(k);if(v!==null)payload[k]=sanitizeStore(parse(v))});return payload}
function mergePreservingRemoteUnsafe(localPayload,remotePayload){const out={...localPayload};KEYS.forEach(k=>{const remoteUnsafe=unsafeRows(remotePayload?.[k]);if(!remoteUnsafe.length)return;const local=Array.isArray(out[k])?out[k]:[];out[k]=[...local,...remoteUnsafe]});return out}
function storeStats(payload=snapshot()){return KEYS.map(k=>{const v=payload[k];let count=0;if(Array.isArray(v))count=v.length;else if(v&&typeof v==='object')count=Object.keys(v).length;else if(v!=null)count=1;return{key:k,present:Object.prototype.hasOwnProperty.call(payload,k),count}})}
function meta(){try{return JSON.parse(localStorage.getItem(META)||'{}')}catch{return{}}}
function setMeta(patch){const m={...meta(),...patch};localStorage.setItem(META,JSON.stringify(m));return m}
function emit(state,detail={}){window.dispatchEvent(new CustomEvent('hd20-db-status',{detail:{state,at:new Date().toISOString(),...detail}}))}
function notify(source='supabase'){['hd20-db-synced','hd20-kpi-source-updated','hd20-gmes-5s-imported','hd20-gmes-5s-judged','hd20-action-updated','hd20-audit-updated'].forEach(name=>window.dispatchEvent(new CustomEvent(name,{detail:{source}})))}
function apply(payload){if(!payload||typeof payload!=='object')return;applying=true;try{KEYS.forEach(k=>{if(Object.prototype.hasOwnProperty.call(payload,k)){const clean=sanitizeStore(payload[k]);localStorage.setItem(k,typeof clean==='string'?clean:JSON.stringify(clean))}})}finally{applying=false}notify()}
async function fetchRemote(){if(!client||!user)return null;const {data,error}=await client.from('hd20_app_state').select('payload,updated_at,updated_by').eq('id',ROW).maybeSingle();if(error){emit('error',{message:error.message});console.error('[HD20 DB] fetch',error);return null}return data||null}
async function pull(){emit('syncing',{mode:'pull'});const data=await fetchRemote();if(data?.payload&&Object.keys(data.payload).length){apply(data.payload);lastRemoteAt=data.updated_at||'';setMeta({lastPullAt:new Date().toISOString(),remoteUpdatedAt:lastRemoteAt});emit('ready',{mode:'pull',remoteUpdatedAt:lastRemoteAt,stores:storeStats(data.payload)});return data}emit('ready',{mode:'pull',empty:true,stores:storeStats({})});return data}
async function push(){if(!client||!user||applying)return false;emit('syncing',{mode:'push'});const remote=await fetchRemote(),m=meta();if(remote?.updated_at&&m.remoteUpdatedAt&&remote.updated_at!==m.remoteUpdatedAt){apply(remote.payload||{});lastRemoteAt=remote.updated_at;setMeta({lastPullAt:new Date().toISOString(),remoteUpdatedAt:remote.updated_at,conflictResolvedAt:new Date().toISOString()});emit('ready',{mode:'conflict-pull',remoteUpdatedAt:remote.updated_at,stores:storeStats(remote.payload||{})});return false}const cleanLocal=snapshot(),payload=mergePreservingRemoteUnsafe(cleanLocal,remote?.payload||{}),stamp=new Date().toISOString();const {data,error}=await client.from('hd20_app_state').upsert({id:ROW,payload,updated_by:user.id,updated_at:stamp},{onConflict:'id'}).select('updated_at').single();if(error){emit('error',{message:error.message});console.error('[HD20 DB] push',error);return false}lastRemoteAt=data?.updated_at||stamp;setMeta({lastPushAt:new Date().toISOString(),remoteUpdatedAt:lastRemoteAt});emit('ready',{mode:'push',remoteUpdatedAt:lastRemoteAt,stores:storeStats(cleanLocal)});return true}
async function manualSync(){if(!ready)return false;const btn=document.getElementById('hd20DbSyncNow');if(btn){btn.disabled=true;btn.textContent='동기화중…'}try{const remote=await fetchRemote(),local=snapshot(),hasRemote=!!(remote?.payload&&Object.keys(remote.payload).length),hasLocal=Object.keys(local).length>0;if(!hasRemote&&hasLocal)return await push();if(hasRemote){apply(remote.payload);lastRemoteAt=remote.updated_at||'';setMeta({lastPullAt:new Date().toISOString(),remoteUpdatedAt:lastRemoteAt});emit('ready',{mode:'manual-pull',remoteUpdatedAt:lastRemoteAt,stores:storeStats(remote.payload)});return true}emit('ready',{mode:'manual-empty',stores:storeStats(local)});return true}finally{if(btn){btn.disabled=false;btn.textContent='DB 동기화'}}}
function queue(){if(!ready||applying)return;clearTimeout(timer);timer=setTimeout(push,500)}
function patchStorage(){if(patched)return;patched=true;const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){original.call(this,k,v);if(this===localStorage&&KEYS.includes(k))queue()}}
function installBadge(){const controls=document.querySelector('.controls');if(!controls)return;let badge=document.getElementById('hd20DbStatus');if(!badge){badge=document.createElement('span');badge.id='hd20DbStatus';badge.className='hd20DbStatus';badge.textContent='DB 연결 확인중';controls.appendChild(badge)}let btn=document.getElementById('hd20DbSyncNow');if(!btn){btn=document.createElement('button');btn.id='hd20DbSyncNow';btn.type='button';btn.className='hd20DbSyncNow';btn.textContent='DB 동기화';btn.onclick=manualSync;controls.appendChild(btn)}if(!badge.dataset.bound){badge.dataset.bound='1';window.addEventListener('hd20-db-status',e=>{const s=e.detail?.state,stores=e.detail?.stores||[];if(s==='syncing'){badge.textContent='DB 동기화중';badge.dataset.state='syncing'}else if(s==='error'){badge.textContent='DB 오류';badge.dataset.state='error'}else{badge.textContent='DB 연결됨';badge.dataset.state='ready'}if(stores.length)badge.title=stores.map(x=>`${x.key}: ${x.present?'연결':'없음'} (${x.count})`).join('\n')})}}
async function boot(){if(window.HD20_AUTH_BYPASS)return;if(booting)return;booting=true;try{client=window.HD20_SUPABASE;if(!client){booting=false;setTimeout(boot,120);return}const {data}=await client.auth.getSession();user=data?.session?.user||null;if(!user)return;installBadge();patchStorage();const localBefore=snapshot(),hasLocal=Object.keys(localBefore).length>0;const remote=await fetchRemote(),hasRemote=!!(remote?.payload&&Object.keys(remote.payload).length);ready=true;if(hasRemote){apply(remote.payload);lastRemoteAt=remote.updated_at||'';setMeta({lastPullAt:new Date().toISOString(),remoteUpdatedAt:lastRemoteAt});emit('ready',{mode:'initial-pull',remoteUpdatedAt:lastRemoteAt,stores:storeStats(remote.payload)});const hydrateKey='hd20-db-hydrated:'+user.id;if(!sessionStorage.getItem(hydrateKey)){sessionStorage.setItem(hydrateKey,lastRemoteAt||'1');setTimeout(()=>location.reload(),80)}}else if(hasLocal){await push()}else emit('ready',{mode:'empty',stores:storeStats({})});window.HD20_DB_SYNC={pull,push,manualSync,fetchRemote,keys:[...KEYS],stats:()=>storeStats(),ready:()=>ready,status:()=>({ready,lastRemoteAt,meta:meta(),stores:storeStats()})}}finally{booting=false}}
window.addEventListener('hd20-auth-ready',e=>{user=e.detail?.user||user;boot()});window.addEventListener('hd20-auth-bypass',()=>{window.HD20_DB_SYNC={pull:async()=>null,push:async()=>false,manualSync:async()=>false,keys:[...KEYS],stats:()=>storeStats(),ready:()=>false,status:()=>({ready:false,bypass:true,stores:storeStats()})}});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,100),{once:true}):setTimeout(boot,100);
})();